### ISSUE TITLE
Cannot compile NDK project

### ISSUE THREAD

**Issue by IgorGanapolsky** [android-ndk/ndk#102]
I imported the Hello-libs git example from Github.  I cannot compile the project.  Console keeps spewing error:
> Error:(1, 1) A problem occurred evaluating project ':app'.
> java.lang.NoClassDefFoundError: com/android/build/gradle/internal/NdkHandler

See screenshot:
<img width="1420" alt="screen shot 2016-05-23 at 9 53 01 am" src="https://cloud.githubusercontent.com/assets/201209/15473069/2746baa8-20cc-11e6-972f-2818b95f5fe4.png">

**Comment by DanAlbert** [comment]
What version of the NDK are you using? It sounds like it's either a bug in the gradle plugin, or perhaps just the wrong version of the gradle plugin. Might need the experimental one?

Unfortunately we don't know anything about the gradle side of things since that's not actually a part of the NDK. If the experimental plugin doesn't work, should probably file a bug for the studio folks at http://b.android.com.

**Comment by IgorGanapolsky** [comment]
I am on NDK version **Pkg.Revision = 12.0.2867246-beta2**.  Does it matter?  I am indeed using gradle experimental:
`classpath 'com.android.tools.build:gradle-experimental:0.7.0'`

**Comment by DanAlbert** [comment]
I don't think it would should make a difference (not one that would cause that error, anyway), but it would be good to include that information in your report for Studio just in case.

Going to close this since I don't think there's anything to be done on the NDK side of things.

**Comment by IgorGanapolsky** [comment]
@DanAlbert Did you verify that it works in A.S. 2.2 Preview 1 on your machine?

**Comment by DanAlbert** [comment]
See my comment above:

> ... should probably file a bug for the studio folks at http://b.android.com.

We only handle NDK things, not Gradle/Studio.
