### ISSUE TITLE
simpleperf similar loads and stores numbers

### ISSUE THREAD

**Issue by behnampn** [android-ndk/ndk#1033]
I noticed Simpleperf reports almost similar number for L1-dcache-loads and L1-dcache-stores  for all applications. So, I don't know if it is an issue with the tool or something related to the system architecture or I'm doing something wrong.

System:
Nexus 6P (arm) Android 6.0.1

Setup:
build arm executable with NDK r12 (use clang to build executable from c++ source code)
push executable to device (using adb)
push simpleperf (from latest NDK version r20) to the device (using run_simpleperf_on_device script).
run command "simpleperf stat -e L1-dcache-loads,L1-dcache-stores [executable]"

Output example:
Performance counter statistics:

  7,252,503,343  L1-dcache-loads    #   (100%)
  7,252,503,302  L1-dcache-stores   #   (100%)

Total test time: 16.847543 seconds.

**Comment by yabinc** [comment]
It's because on Nexus 6P, L1-dcache-loads and L1-dcache-stores are mapped to the same hardware event in the kernel. In ARM arch manual, L1D_CACHE, L1D_CACHE_WB, L1D_CACHE_RD are defined as PMU events. But there is no guarantee which events are available on device. The early version kernel maps both cache read and write to L1D_CACHE, so they are the same. The latest kernels add the ability to map cache read to L1D_CACHE_RD and write to L1D_CACHE_WB, if the two events are available.

The early kernel patch is in https://lkml.org/lkml/2012/7/6/559:
+static const unsigned armv8_pmuv3_perf_cache_map[PERF_COUNT_HW_CACHE_MAX]
+						[PERF_COUNT_HW_CACHE_OP_MAX]
+						[PERF_COUNT_HW_CACHE_RESULT_MAX] = {
+	[C(L1D)] = {
+		[C(OP_READ)] = {
+			[C(RESULT_ACCESS)]	= ARMV8_PMUV3_PERFCTR_L1_DCACHE_ACCESS,
+			[C(RESULT_MISS)]	= ARMV8_PMUV3_PERFCTR_L1_DCACHE_REFILL,
+		},
+		[C(OP_WRITE)] = {
+			[C(RESULT_ACCESS)]	= ARMV8_PMUV3_PERFCTR_L1_DCACHE_ACCESS,
+			[C(RESULT_MISS)]	= ARMV8_PMUV3_PERFCTR_L1_DCACHE_REFILL,
+		},

And it was fixed in 2017 in patches starting from https://gitlab.denx.de/Xenomai/ipipe-ppc32/commit/d0d09d4d99e08767050bc30f2b19d6146abe01e2.
The patch seems to arrive at kernel 4.4. But there is no tests to ensure Android devices have it.

For work-around:
Linux kernel wraps hardware event numbers into common numbers, but it also supports raw hardware numbers. Simpleperf has the ability to detect hardware event numbers available on device. You can use `simpleperf list raw` to show raw ARM PMU numbers available on device and use them.
For example, you can use raw-l1-dcache-wb for cache writes on Nexus 6P.
For l1-dcache-rd. simpleperf doesn't support detecting it yet (I will fix it soon).

For fixes:
We can add logic in simpleperf to replace perf events with better raw hardware events if they are available on device.

**Comment by behnampn** [comment]
Thank you. Very helpful.

**Comment by yabinc** [comment]
After experiment, I verified that simpleperf accepts r40 as the event name for l1-dcache-rd. Because 0x40 is the event number for L1D_CACHE_RD in arm manual. That could be used as a work-around.
