### ISSUE TITLE
[BUG] Building with APP_STL := c++_static produces library that requires libc++_shared.so

### ISSUE THREAD

**Issue by jfpoole** [android-ndk/ndk#1056]
#### Description

When building a shared library with NDK r20 ndk-build and setting `APP_STL := c++_static` the resulting library still requires `libc++_shared.so` (the resulting APK crashes with the exception `java.lang.UnsatisfiedLinkError: dlopen failed: library "libc++_shared.so" not found`).

The same project builds without issue with NDK r19c.

The same project builds without issue with NDK r20 and with `APP_STL := c++_shared`.

I don't have a small test case I can share for this issue yet (sorry!) but I'm wondering if this is a known issue or a case where I'm holding it wrong?

#### Environment Details

* NDK Version: Android NDK r20
* Build system: ndk-build
* Host OS: macOS 10.14.6
* ABI: arm64-v8a
* NDK API level: 21
* Device API level: 26

**Comment by DanAlbert** [comment]
An ndk-build hello world shows otherwise, so this has something to do with your configuration. You can try `readelf -dW $LIB | grep NEEDED` on all of your libraries to figure out which one has the dependency and work from there.

Closing since this doesn't appear to be an NDK bug, but happy to answer more questions if they come up.
