### ISSUE TITLE
[question]Why only armeabi uses the "-Os" optimization option？

### ISSUE THREAD

**Issue by foundkey** [android-ndk/ndk#1059]
My team use NDK(r12b) build some *.so, that require compression space. In the “ android.toolchain.cmak" file, I find NDK defual use "-O2" option in release build and only “armeabi" use "-Os“. Why? Can I use "-Os” option with other ABI？

============
NDK: r12b
ABI: arm64-v8a
Ubuntu 18.04 + AS 3.4.2 + Gradle 3.4.1

**Comment by DanAlbert** [comment]
The only answer I have is "because that's the way it's always been". It dates back to the original checking of ndk-build in to git: https://android.googlesource.com/platform/ndk/+/48ef1859ef0bb25547e5aceeedb9b175c6193bc5/build/toolchains/arm-eabi-4.2.1/setup.mk#49. Since it's been that way for so long, it would be disruptive to do otherwise.

> Can I use "-Os” option with other ABI？

Sure. Note that if you're using Clang (you're on an extremely old NDK, so maybe not) you actually want `-Oz`, not `-Os`.
