### ISSUE TITLE
[question] what is the meaning of cpu-cycles event records?

### ISSUE THREAD

**Issue by zfk0531** [android-ndk/ndk#1064]
Hi, when i use simpleperf to profile android applications, I get the cpu cycles event which is a integer number. So, my question is what does this number mean? Is this the number of cycles that cpu takes to run the top function in the call stack? 
My second question is that does the timestamp record the start time of the event? We can use the -f parameter to set the frequency of samples in one second. Does these samples are taken in a uniform interval or according to the period of the event?

**Comment by yabincui** [comment]
cpu-cycles event means how many cpu cycles are used to run a program.
The number is accurate when you are using stat command to only get numbers.
But for record command, it is not that accurate. Because we are doing sampling instead of tracing.

In record command, if using -c 10000, it means to record a sample every 10000 cpu-cycles passed. The sample hits a function, and we assume all the 10000 cycles are spent in that function. It may not be true. But if we have many samples hit a function, the function probably is hot.
So we assume the number is the cpu cycles taken to run the top function in the call stack, while it isn't true or accurate. Because we are doing sampling instead of tracing.

The timestamp is the time we generate a sample record. Each sample record has a timestamp. When using -f option, the samples are not guaranteed to be taken in a uniform interval. For -f 1000,
we are asking to take about 1000 samples every second the program running. And the kernel needs to adjust sample period dynamically to fulfill this need as much as possible. So the sample period will change dynamically.
