### ISSUE TITLE
internal compiler errors should direct bug-filers to github, not llvm.org

### ISSUE THREAD

**Issue by froydnj** [android-ndk/ndk#115]
As seen in #114, the message for internal compiler errors says:

```
clang++: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
```

This message should direct people to https://github.com/android-ndk/ndk/issues or similar.

**Comment by stephenhines** [comment]
It probably is better to actually file bugs like that against upstream LLVM (or even both places and just include a link between them). Including all the relevant pieces (shell script and preprocessed source) usually lets them reproduce the problem much more quickly (since this is likely for a specific device target, and not a general compiler bug). Our team generally directs most bugs like this at upstream LLVM in any case.
