### ISSUE TITLE
in_port_t is never defined

### ISSUE THREAD

**Issue by fornwall** [android-ndk/ndk#123]
http://pubs.opengroup.org/onlinepubs/000095399/basedefs/netinet/in.h.html says:

```
The <netinet/in.h> header shall define the following types:

in_port_t
Equivalent to the type uint16_t as defined in <inttypes.h> .
in_addr_t
Equivalent to the type uint32_t as defined in <inttypes.h> .
```

but `in_port_t` is never defined by any NDK header.

**Comment by enh** [comment]
added to bionic in the L timeframe: https://android.googlesource.com/platform/bionic/+/35d226e05d92824c6eb992e7a64ea22efc8bae03

unfortunately, the NDK L headers are not actually the platform L headers, and the NDK's M and N headers are just copies of the NDK's L headers.

this will be fixed by https://github.com/android-ndk/ndk/issues/120
