### ISSUE TITLE
32-bit Windows NDK has 64-bit Clang

### ISSUE THREAD

**Issue by WyvernWang** [android-ndk/ndk#139]
I found the filename of NDK download for 32bit windows and 64 bit windows are exchanged.
But in the end, both are 64 bits cause I get the same error message in my 32 bit windows system
![default](https://cloud.githubusercontent.com/assets/13504385/16438260/9b6ce336-3de0-11e6-9c3e-610ae094dd47.PNG)
![2](https://cloud.githubusercontent.com/assets/13504385/16438462/87dbce3e-3de2-11e6-956b-16538efa9036.PNG)

**Comment by rmtheis** [comment]
@WyvernWang see #127.

**Comment by DanAlbert** [comment]
The official page is also out of date. Should just get downloads from https://github.com/android-ndk/ndk/wiki#current-stable-release since I can actually update that one myself.

I have patches up to fix the mismatch, but they haven't been submitted yet (and the website has to wait for pushes as well).

As for the 64-bit executable, that's actually news to me. We still have the 32-bit only windows clang mentioned as a bug in our changelog, but apparently that got fixed (and the 32-bit one broken in the process) and I didn't know that. @stephenhines, did we make a change to be building *only* 64-bit Windows clang?

**Comment by DanAlbert** [comment]
Well, if I go build clang myself the Windows one is certainly 64-bit, but the one in `prebuilts/clang/host/windows-x86` definitely is 64-bit... I'm going to go check others on the build server. It seems unlikely that this is a configuration issue, but I suppose it's possible.

**Comment by DanAlbert** [comment]
I lied. I thought I'd synced my tree but I forgot to authenticate first so it was still a tree from March.

I was able to figure out what happened based on build server history and the git logs though: https://android-review.googlesource.com/#/c/208822/

So we actually do build a 64-bit Clang now. Rather than being two separate installs though, `clang.exe` is 64-bit and we have a `clang_32.exe` that is 32-bit, rather than two separate install directories like we needed :|

I'll have to chat with @stephenhines to see what we can do about this. Recent clang/llvm changes means we can't actually build a new clang for Windows until we sort out some mingw issues.

**Comment by DanAlbert** [comment]
https://android-review.googlesource.com/#/c/245136/

It'll at least be fixed in r13. We don't have any plans for an r12c yet, but if we end up with one this will get cherry-picked.
