### ISSUE TITLE
Including <openssl> header files

### ISSUE THREAD

**Issue by cRAN-cg** [android-ndk/ndk#147]
I am currently porting a network protocol with its core originally written in c++. My build shows errors with the missing `<openssl/sha.h>` file. I wanted some suggestions/tips so as to make it work. Thanks :)

**Comment by DanAlbert** [comment]
Openssl is not a part of the NDK. You'll need to import it as a third party library into your app. http://stackoverflow.com/q/2952572/632035 looks like it might be useful for getting started. I'd recommend only following the build instructions you find there and getting the source yourself. It'd be far too easy an attack vector to trust some arbitrary copy of openssl from github.

FWIW, getting an NDK-ready version of boringssl/openssl up is something we want to do some day since it is a really commonly needed library, but we haven't had the time yet.

**Comment by youaresoomean** [comment]
@DanAlbert Is there any update regarding an NDK-ready version of boringssl/openssl? Why every NDK app has to include it's own version of openssl? (including all the hassel to build it)

**Comment by DanAlbert** [comment]
No, we haven't had time to make a cdep package yet. Not sure if the community has built one.
