### ISSUE TITLE
size issue of static library 

### ISSUE THREAD

**Issue by lcwyylcwyy** [android-ndk/ndk#169]
I encounter an issue that 
when I compile the my static library source with `ndk-build V=1` , 
whether I use  `NDK_DEBUG=1` or `0`,
the g++ alway has `-g` flag .

Because in every toolchain setup.mk , 
the `TARGET_xxx_release_CFLAGS`  assignment has `-g` flag. 

So my static library size become very large.
And I used objdump to check the .o file, It has many debug info.  

How to delete the `-g` flag writen in setup.mk through Android.mk or Application.mk

**Comment by Evisceration** [comment]
As workaround, you can specify `-g0`.

Taken from `man gcc`

> Level 0 produces no debug information at all.
> Thus, -g0 negates -g.

**Comment by DanAlbert** [comment]
The size of a static library is irrelevant though since it isn't a part of an app. When the library gets linked into a shared library or executable, `ndk-build` runs `strip` on the output which removes all the debug info.

**Comment by lcwyylcwyy** [comment]
Thank you ! @Evisceration 
@DanAlbert Thanks a lot for your answer!   I know the `strip` function. But if my team distribute our libs to other company, I must add `-g0` flag in release version.  We can not control it through `NDK_DEBUG=0` that we hope to.

**Comment by vltmrkls** [comment]
I had to deal with the same issue...

this worked for me:
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -g0")

**Comment by DanAlbert** [comment]
(saw your comment on the other thread, but repeating a bit here for those that didn't)

If you care about the size of your static libraries (for distribution, CI artifact bills, etc) and _don't_ care about debugging, disabling debug info will save a lot, yeah. I don't think the compilers are generally are very concerned with keeping down the size of static libraries since they're intermediate artifacts, so YMMV.

It does mean you won't be able to debug though.
