### ISSUE TITLE
`APP_SHORT_COMMANDS` doesn't work with `NDK_OUT` on Windows.

### ISSUE THREAD

**Issue by chaoren** [android-ndk/ndk#186]
Set `LOCAL_SHORT_COMMANDS=true` or `APP_SHORT_COMMANDS=true`, then set `NDK_OUT=C:\some\windows\path`. Build fails because the `NDK_OUT` path is embedded directly into the response file, and the compiler will interpret the slashes as escapes. We need to fix up these paths before putting them into response files.

**Comment by DanAlbert** [comment]
https://android-review.googlesource.com/#/c/270895/

**Comment by alyawn** [comment]
A related issue is still happening on my project that uncovered another spot in `build-binary.mk` that fails while building a shared library on windows due to path escaping being missing: https://android.googlesource.com/platform/ndk/+/refs/heads/master/build/core/build-binary.mk#713

I fixed locally with the following on line 713:

        $(call generate-list-file,$(call escape-backslashes,$(linker_options)),$(linker_list_file))


Either this should be re-opened or a new issue should probably be created. Thoughts?

**Comment by DanAlbert** [comment]
New issue please (or upload a patch to gerrit if you prefer)
