### ISSUE TITLE
r11: some commands removed from NDK_ROOT

### ISSUE THREAD

**Issue by khirowatari** [android-ndk/ndk#19]
ndk-which: not included in archive.
ndk-stack / ndk-depends / ndk-gdb.py: moved under prebuilt/(platform)/bin dir.

Why removed from NDK_ROOT ?

**Comment by DanAlbert** [comment]
We're working on packaging things differently to play nice with the SDK manager, and doing so required moving things into their own directories. `ndk-build` had a workaround added since that seemed important enough to warrant it.

I can add similar wrappers for `ndk-gdb`, `ndk-depends`, and `ndk-stack` easily enough.

`ndk-which` was an omission. I'll get it into r11b (same for the wrappers).

**Comment by DanAlbert** [comment]
https://android-review.googlesource.com/#/c/207992/
https://android-review.googlesource.com/#/c/207993/

**Comment by DanAlbert** [comment]
r11b is live with the fixes: http://developer.android.com/ndk/downloads/index.html#download
