### ISSUE TITLE
cmake 3.6.3155560 doesn't run on Fedora 23

### ISSUE THREAD

**Issue by diegorondini** [android-ndk/ndk#206]
cmake 3.6.3155560 provided by Android SDK doesn't run on Fedora 23, fails with the error:
`$ ./android-sdk-linux_x86/cmake/3.6.3155560/bin/cmake 
./android-sdk-linux_x86/cmake/3.6.3155560/bin/cmake: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory`
I think this is because it assumes Debian / Ubuntu style packaging, but there is no "libssl.so.1.0.0" in Fedora:
`# ls -1 /usr/lib64/libssl*
/usr/lib64/libssl3.so
/usr/lib64/libssl.so
/usr/lib64/libssl.so.10
/usr/lib64/libssl.so.1.0.2h`

Same thing applies to `libcrypto.so.1.0.0`:
`$ ./android-sdk-linux_x86/cmake/3.6.3155560/bin/cmake 
./android-sdk-linux_x86/cmake/3.6.3155560/bin/cmake: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory`

**Comment by DanAlbert** [comment]
This looks like a dup of https://code.google.com/p/android/issues/detail?id=212007

**Comment by Huatian** [comment]
I have meet the same problem.

**Comment by erlogerik** [comment]
Same problem here, are there any fixes?

**Comment by DanAlbert** [comment]
See my post above. Follow along on the other bug. The NDK does not ship cmake, so there's nothing we can do about it.

**Comment by Schmerzmittel** [comment]
Same bug on Fedora 24. I believe we should wait for Fedora developers to fix this bug.

**Comment by bc-lee** [comment]
I believe that is due to some symbol issues between Ubuntu (which is Google's primary and only distro) and Fedora. Large amount of pre-compiled binaries from Ubuntu make such issues.

Workaround from [(Gist) Install Spotify on Fedora](https://gist.github.com/olejon/54473554be2d4dbacd03):
Download libssl.so.1.0.0 and libcrypto.so.1.0.0 :(

I'm using Fedora 25 and it works for me.
