### ISSUE TITLE
Why NDK r13 android.toolchain.cmake add -fno-exceptions and -fno-rtti?

### ISSUE THREAD

**Issue by JimmyTeng** [android-ndk/ndk#212]
I will transplant a CMAKE  c++ project with typeid and exception , is NDK r13 support these ?

**Comment by DanAlbert** [comment]
@chaoren, any idea if this was intentional? It looks like we tried to match the behavior of https://github.com/taka-no-me/android-cmake/blob/master/android.toolchain.cmake#L832, but we don't default the option to `ON`.

ndk-build defaults to no exceptions or RTTI support, so it's possible the goal was to match that.

For now, it looks like you can add `-DANDROID_CPP_FEATURES="rtti exceptions"` when invoking cmake to get the behavior you want.

**Comment by chaoren** [comment]
> ndk-build defaults to no exceptions or RTTI support, so it's possible the goal was to match that.

Yep, this is it. I also had a chat with @vharron, and we kind of decided that these are pretty bloaty features to have on by default on Android.

**Comment by DanAlbert** [comment]
Sounds reasonable to me. As noted above, `-DANDROID_CPP_FEATURES="rtti exceptions"` can be passed to enable these features.

**Comment by bog-dan-ro** [comment]
Why don't you do the other way around?
Let all the features compilers features as they are and use -DANDROID_CPP_DISABLE_FEATURES="rtti exceptions" to disable them.
Actually ANDROID_CPP_DISABLE_FEATURES is not needed at all, because most of the people that are using cmake and they really don't want to use rtti & exceptions in their C++ projects are disabling  themselves.

IMHO, disabling rtti and exceptions in the toolchain is simply wrong, this decision can be done in the project cmake scripts if is needed not in the toolchain file.

**Comment by DanAlbert** [comment]
> this decision can be done in the project cmake scripts if is needed not in the toolchain file.

This is a very good point. Given that we went with cmake because it's already common in the wild, we should probably be behaving the way all those existing cmake systems expect.

I can fix this simply enough on our side, but I'm guessing Studio will auto set this option when configuring a new project, so I'll need to look in to that.

**Comment by JimmyTeng** [comment]
Thx This is a great help

**Comment by JimmyTeng** [comment]
And another problem is android.toolchain.cmake could config CMAKE_INSTALL_PATH, so when other project need to find Find***.cmake , it could not work in right way. What should I do ?

**Comment by DanAlbert** [comment]
This is in r14 beta 1.
