### ISSUE TITLE
#include<map> gives static_assert failed error on compile

### ISSUE THREAD

**Issue by intelzombi** [android-ndk/ndk#214]
Using Android Studio to update the SDK and NDK  (12.1.2977051 to 13.0.3315539) I am now getting a compile error with the latest R13 at the point:
`#include<map>`
sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/include/map:820:5: error: static_assert failed "Allocator::value_type must be same type as value_type"
    static_assert((is_same<typename allocator_type::value_type, value_type>::value),

Reverting to the earlier 12.1.... version resolves the issue.

**Comment by DanAlbert** [comment]
The libc++ in r13 includes some checks like this one to guard against undefined behavior that can arise through misuse of `std::map` (and a few other types).

Most often this `static_assert` fires because your map is `<Key, const T>` and your allocator is `<const Key, T>`. The fix is to make the allocator `<const Key, const T>`.

We had to fix a number of these issues when updating the platform code to this version of libc++, and we didn't see any cases where this `static_assert` was misfiring. Please re-open if you think it is.

**Comment by intelzombi** [comment]
Thank You Dan,
upon review we did find that the key in the allocation was being passed in from a non const static variable.

typedef std::map<const int, MemoryBlock64*> memoryMap

in the constructor we had
const int PointerMap::AllocateMemoryBlock(const int size)
{
	static int s_blockGuid = 0;
	s_blockGuid++;
	MemoryBlock64* block = new MemoryBlock64(size);
	m_memoryMap[s_blockGuid] = block;
	return s_blockGuid;
}

I'm not entirely sure why this isn't a legal allocation other than the static int isn't a const but that wouldn't keep the actual key from being a const.  It works fine on all other platforms (Mac, Windows, IOS, Linux)  so why is Android is the odd man out?  
but we don't necessarily have to have a const key but the Value cannot be const in our case. 
However changing the kvp to std::map<int,MemoryBlock64*> doesn't resolve the compile issue. 

Thanks for your help on this.  If you have any further educational tips on this topic we are all ears. Do we need to keep this issue open?

**Comment by DanAlbert** [comment]
> we don't necessarily have to have a const key but the Value cannot be const in our case.

That should be fine, it's just important that your container and your allocator agree about the const-ness of the key/value pair.

> I'm not entirely sure why this isn't a legal allocation other than the static int isn't a const but that wouldn't keep the actual key from being a const.

To map the `static_assert` to the relevant piece of the spec (n3797 23.2.1.14):

> In Table 99, X denotes an allocator-aware container class with a value_type of T using allocator of type A, u denotes a variable, a and b denote non-const lvalues of type X, t denotes an lvalue or a const rvalue of type X, rv denotes a non-const rvalue of type X, and m is a value of type A.
> ...
> Requires:allocator_-type::value_type is the same as X::value_type.

`X::value_type` (in this case `memoryMap::value_type`) is `std::pair<const int, MemoryBlock64*>`.

Is the sample you provided above (`typedef std::map<const int, MemoryBlock64*> memoryMap;`) complete? This `static_assert` should only be tripped if you're actually defining a custom allocator for the container. Going to re-open assuming the sample above is correct, because I would think that what you've shown would work.

> so why is Android is the odd man out?

Because Android is the most up to date :) That check was added fairly recently. Windows doesn't use libc++, and while Mac and iOS do, they don't have this version yet.

**Comment by intelzombi** [comment]
Thanks for added context.   So we've actually come across quite a few issues with this new assert.  We found some areas where the allocator was being declared int the typedef as allocator<k,v> instead of allocator<const k, v>   We were able to fix that however we are now experiencing a compile error later in our build that is in code that we actually created so it's a bit more personal now :).      

We are not sure why we are getting an error with the assert here.  We believe we are following the rules. 
This one is complaining about an allocator where we use a "placement" new for a leaky Impl pattern.  

`typedef std::map<void*, OurClassMap, std::less<void*>,
		OurAllocator<std::pair<const void*, OurClassMap>>> OurClassMap;`

followed by
`{
        static OurClassMap* spOurClassMap = nullptr;
	if (!spOurClassMap)
	{
		// Use placement new in case an app's global operator new override uses VirtualAlloc.
		void* p = malloc(sizeof(*spOurClassMap));
		spOurClassMap = new (p) OurClassMap();
	}
	return *spOurClassMap; 
}`

The compiler is complaining at the malloc line.
`cxx-stl/llvm-libc++/include/map:820:5: error: static_assert failed "Allocator::value_type must be same type as value_type"
    static_assert((is_same<typename allocator_type::value_type, value_type>::value),`

.cpp:302:26: note: in instantiation of template class 'std::__ndk1::map<void *, (anonymous namespace)::OurMappedRegion, std::__ndk1::less<void *>,
      ASL::ASL_MallocAllocator<std::__ndk1::pair<const void *, (anonymous namespace)::OurMappedRegion> > >' requested here
                void* p = malloc(sizeof(*spOurClassMap));

I've got more errors than the compiler will spit out but this is the first in the list.  
Is it possible that the assert has issues with "placement" new?
Clues?
Thanks

**Comment by intelzombi** [comment]
``

**Comment by intelzombi** [comment]
So we figured this out.
our typedef was incorrect.
typedef std::map<void*, OurClassMap, std::less<void*>, OurAllocator<std::pair<const void*, OurClassMap>>> OurClassMap;

we changed it to:

typedef std::map<void*, OurClassMap, std::less<void*>, OurAllocator<std::pair<void* const, OurClassMap>>> OurClassMap;

it compiled and life is good
