### ISSUE TITLE
Update zlib.h version

### ISSUE THREAD

**Issue by fornwall** [android-ndk/ndk#230]
The `<zlib.h>` header in the NDK is for version 1.2.3 of zlib on all API levels.

The system zlib is higher than that:

- [On gingerbread it seems to be 1.2.5](https://android.googlesource.com/platform/external/zlib/+/gingerbread-release/zlib.h).
- [Starting from kitkat, version 1.2.8](https://android.googlesource.com/platform/external/zlib/+/android-4.4_r1/src/zlib.h). 

Could the `<zlib.h>` file in the NDK be bumped to 1.2.5 for all API levels (and if possible, to 1.2.8 starting from android-19)?

**Comment by DanAlbert** [comment]
We'll be shipping exactly what we have in the platform with unified headers (r14's main feature), which is 1.2.8: https://android.googlesource.com/platform/external/zlib/+/master/src/zlib.h

So the good news is that this is actually more or less done :) I still need to iron out the kinks and get it shipped though.

**Comment by DanAlbert** [comment]
Somewhat longer term it would probably be beneficial to ship actual zlib in the NDK (rather than the stub system lib) so you're never stuck using an old zlib; a new one will just ship in your app.

**Comment by DanAlbert** [comment]
Just an update: this actually won't be in r14-beta1. We can't trivially use the up to date header for all target API levels because code checking the zlib version from the header will expect to find new APIs that weren't there on gingerbread.

We might just fix up the header to conditionally define the zlib version based on the target API level.

Alternatively, we've been considering removing zlib as a platform API and shipping a full zlib in the NDK instead. It would be shipped as sources/third_party/zlib. It would need to be included in the user's app, but has the advantage of being able to use a new version of zlib even when targeting gingerbread.

**Comment by ehem** [comment]
Note that not everyone needs the newer zlib.  If one is using functionality which is present in all versions of zlib, bundling in a copy of the latest version unnecessarily makes the APK and installed size bigger.

**Comment by rcdailey** [comment]
@DanAlbert I'm getting weird `_Unwind_Resume` crashes in my tombstone files pointing at `libz.so`:

```
    #00  pc 00010604  /system/lib/libz.so (__gnu_Unwind_Resume+8)
    #01  pc 00010898  /system/lib/libz.so (_Unwind_Resume+20)
```

Not sure why, but I wanted to make sure I'm using the right libz.so library. The one I'm using is here:

    <NDK>/platforms/android-15/arch-arm/usr/lib/libz.so

And my toolchain file used with CMake 3.9.0 (should tell you my configuration):

```
set( CMAKE_SYSTEM_NAME Android )
set( CMAKE_SYSTEM_VERSION 15 ) # API level
set( CMAKE_ANDROID_ARCH_ABI armeabi-v7a )
set( CMAKE_ANDROID_STL_TYPE c++_shared )
set( CMAKE_ANDROID_NDK_TOOLCHAIN_VERSION clang )
```

I'm using NDK r15b (official release on download page). Is it valid to be using the prebuilt libz.so from the NDK? I don't see one in the unified headers, and I am definitely using the unified headers (not the one in `android-15`)

**Comment by DanAlbert** [comment]
Yeah, libz is one of the things we expose from the system. What device and OS version is this running on?

> Is it valid to be using the prebuilt libz.so from the NDK? I don't see one in the unified headers, and I am definitely using the unified headers

All the libraries still come from the old platforms/ directory rather than from sysroot/, so this is expected.

**Comment by rcdailey** [comment]
It's running on a custom built ARM device from the company I work at. The OS is AOSP Android 17 (Jellybean).

I'm in the process of migrating from gnu stl to LLVM stl and I'm trying to avoid rebuilding as many third party libs as I can. I've rebuilt a few that I know use C++, but others are just C libs (like libpng, which we build, and which we link in the NDK zlib as it requires that).

However this doesn't seem to be related to an ABI compatibility, since zlib is clearly showing up in the tombstone at the very bottom of the backtrace. These issues are incredibly difficult to debug so I'm bugging you in hopes I can identify the issue (for starters, whether its zlib or not)

Thanks for your support and sorry to go slightly off topic. If you have a discussion forum somewhere, where I can get in touch with you, I'd be happy to discuss there instead if you prefer.

**Comment by DanAlbert** [comment]
Having the record here for anyone else running into strange issues is probably useful, but move to another bug to avoid bogging this one down: https://github.com/android-ndk/ndk/issues/457

**Comment by fornwall** [comment]
> Just an update: this actually won't be in r14-beta1. We can't trivially use the up to date header for all target API levels because code checking the zlib version from the header will expect to find new APIs that weren't there on gingerbread.

Now that the NDK master has been updated to require Jelly Bean, can `<zlib.h>` be updated to that of zlib version 1.2.8?

**Comment by DanAlbert** [comment]
Probably can. Will take a look some time for r18.

**Comment by enh** [comment]
(from the git history it looks like i updated external/zlib to 1.2.8 in 2013 but JB shipped in 2012 --- so it's likely that JB-MR2 had 1.2.8 but JB had 1.2.7, and JB-MR1 could be either...)

**Comment by wangpung12** [comment]
Good

**Comment by DanAlbert** [comment]
Should at least be fine to update the header to 1.2.7 for now though.

**Comment by DanAlbert** [comment]
Although I wonder if we can safely assume if all OEMs will also have followed that... I can't think of any reason for them to have gone out of their way to use a different zlib than AOSP, but maybe?

**Comment by DanAlbert** [comment]
https://android-review.googlesource.com/c/platform/development/+/717164

The shared library stub definition makes it look as though the stubs were only ever updated in android-21 (that wouldn't surprise me at all). Going to take some time to look through that list and see what was added between 1.2.3 and 1.2.7...

**Comment by DanAlbert** [comment]
https://android-review.googlesource.com/c/platform/external/zlib/+/717173 fixes the stub library.

**Comment by DanAlbert** [comment]
Merged into r18.
