### ISSUE TITLE
import-module breaks include paths with 13b

### ISSUE THREAD

**Issue by ehem** [android-ndk/ndk#245]
#### import-module breaks include paths with 13b

With 12b doing $(call import-module,android/support) in Android.mk would cause the support library's headers to be added to the include path.  This was broken with 13b.  I can still get the project to build by adding the path to the support module headers to $(LOCAL_C_INCLUDES), but I thought that wasn't supposed to be required.  I guess I'm kind of wondering if that was supposed to be required anyway, but there was a change between 12b and 13b and I don't see it in the Changelog.

I'm referring to 13b, Pkg.Revision = 13.1.3345770.

**Comment by DanAlbert** [comment]
This should be working again in r14: https://android-review.googlesource.com/c/288286/ (https://code.google.com/p/android/issues/detail?id=212634#c8 lists the two changes that causes this).

This had to be broken because ndk-build wasn't actually powerful enough to describe the way to use the project (specifically it had no way of making sure that the headers got included in the right order). The only way to keep libc++ working was to move the logic for the includes into libc++ itself. I've improved ndk-build since then, so we cleaned it back up.

Some history here: `libandroid_support` was pretty much only for making libc++ build. It's not really built to be terribly useful on its own (as you've seen in #236, it's pretty useless for other use cases). r14 will start pushing this in the other direction by at least making it importable if not necessarily useful. Making it useful will be a multi-release effort starting with r15.

**Comment by ehem** [comment]
I was wondering about the headers.  There is an issue that a given project might have several targets and it is quite possible not all of them use a given imported module/library, yet with import-module **all** of them will get the headers (better than none of them, but still).

Interesting handling of the bug DB.  Some groups prefer to have bugs still open until the new code is released, in the hope of duplicates not showing up.  Certainly this is one way.

**Comment by DanAlbert** [comment]
> I was wondering about the headers. There is an issue that a given project might have several targets and it is quite possible not all of them use a given imported module/library, yet with import-module all of them will get the headers (better than none of them, but still).

Modules only get the headers from `import-module` if they actually use the library exporting the headers. If some of the targets don't use the module, they just need to not use the library and they won't get the headers.
