### ISSUE TITLE
Why did you deprecate GCC?

### ISSUE THREAD

**Issue by bog-dan-ro** [android-ndk/ndk#26]
Is it something wrong with GCC 5.x or upcoming 6 on Android that made you to take this decision?
I think is not a good idea to ditch gcc as long as clang still have some issues e.g. #9,  #21.
IMHO having both will not hurt anyone.

**Comment by DoDoENT** [comment]
I can give you my opinions: Clang is faster while compiling source code; has better support for c++14/c++17 and since it is designed primarily as library, it can be used from IDEs like Android Studio to perform static code analysis, refactoring and code completion.

Besides that, Clang is under more permissive open source licence, unlike GCC, which is under GPL. Thus, it is easier to make commercial clang clones which give better support for certain CPU architectures. Also, clang works better with libc++ than GCC, and many native code developers tend to use libc++ because, when compared to GNU stdc++, it has better support for c++14/c++17 STL features and is under permissive BSD-like licence - this makes it possible to use c++14/c++17 features in commercial android apps, like games. GNU stdc++ is under LGPLv3, which makes it impossible to use in commercial apps (yes, stdc++ has special [exception for LGPL](https://gcc.gnu.org/onlinedocs/libstdc++/manual/license.html) which allows usage in commercial apps, provided that you do not modify it - but this makes commercial app development very uncomfortable).

I believe that issues like #21 and #9 will be solved soon.

**Comment by bog-dan-ro** [comment]
You mean that latest clang has better support than gcc **4.9**, right? Because AFAIK gcc 5.x has full [C++14 support](https://gcc.gnu.org/projects/cxx-status.html).

Regarding the licenses IMHO you get it wrong. Personally I prefer GPL because it doesn't allow closed source clones, IMHO is fair to give something when you take so much.
GNU libstdc++ is GPL (NOT LGPL) but the special exception that you've mentioned allows everyone to freely use it and also to **CHANGE IT** as long as the changes made to libstdc++ are made public under GPL. IMHO it is quite stupid to keep these changes for yourself and not to upstream them, because you'll need to maintain them which is not for free.

Least but not last, let's not forget that Google switched to OpenJDK, which is **GPL**, therefore IMHO the licensing issue doesn't stand.

So, GCC was good to build Android for 10 years and now, suddenly is not, and google must ditch it.

**Comment by DoDoENT** [comment]
I just gave my opinions - let the NDK guys give theirs. I think the [tooling support](http://clang.llvm.org/comparison.html) in clang is probably the main reason for switching to it.

**Comment by DanAlbert** [comment]
Licensing actually did not play a significant part in the decision. The other reasons that @DoDoENT mentioned are correct though (yes, GCC 5.x supports C++14, but new features definitely do happen more quickly in clang). The biggest reasons for why we made this decision actually haven't been mentioned though:

> So, GCC was good to build Android for 10 years and now, suddenly is not, and google must ditch it.

Things change. GCC isn't good for Android any more because GCC doesn't provide the same security features that Clang does (and when it does, it provides them much later).

An incomplete list of why the platform switched to clang:
* We make extensive use of integer overflow sanitizers in shipping code to prevent issues like stagefright from recurring
* Address sanitizer and libfuzzer are used widely in testing
* Clang's better diagnostics catch a ton of bugs that GCC does not
* Control flow integrity and safe stacks are being deployed (are deployed?) for even more exploit mitigation.

The fact is that we have significant reason to invest in clang, and splitting effort across maintaining two compilers makes both of them worse.

As it stands now, both compilers are fairly comparable in terms of performance and code size. #21 points at code size increases for armeabi-v7a. That is not always the case, and for every other architecture we actually see smaller code. From some analysis I did when we made this decision for the platform:

> It seems our 32-bit ARM devices are typically 1MB larger (out of 600MB-900MB total), whereas volantis is slightly smaller, and fugu is 15MB smaller. Strangely, sprout_b is also slightly smaller.
>
> I think the ARM32 numbers are small enough to not bother anyone, especially given that it looks like it will be a win for the new devices since they're aarch64.

All the comparisons we did showed that Clang and GCC were pretty much equivalent quality when it came to the code they produced. Yes, sometimes we find cases where GCC is faster, but we also find cases where Clang is faster. As an example, we saw a **20% performance improvement** in the ART interpreter when we switched to clang.

**Comment by DanAlbert** [comment]
@stephenhines might want to add more to this, but I think I covered most of the bases.

**Comment by jcelerier** [comment]
Regarding 

> new features definitely do happen more quickly in clang

As of today, that is not true : GCC has better C++17 compiler than CLang...

http://en.cppreference.com/w/cpp/compiler_support

**Comment by DoDoENT** [comment]
Even more, GCC 6.2 has now faster compile times than clang, while still producing more optimised binary. [Here are benchmarks from Phoronix](https://www.phoronix.com/scan.php?page=article&item=gcc-clang-kblclear&num=1) (see [page 3](https://www.phoronix.com/scan.php?page=article&item=gcc-clang-kblclear&num=3)).

**Comment by stephenhines** [comment]
Thanks for the updates on GCC. We still have no plans to continue maintaining it, but I am glad that others in the community are still working on it.

**Comment by DanAlbert** [comment]
> As of today, that is not true : GCC has better C++17 compiler support than clang...
>
> http://en.cppreference.com/w/cpp/compiler_support

The majority of those features are not in any released version of GCC. Clang hasn't finished it's release cycle either. You have more C++17 with our current Clang than you would with a current GCC, and odds are Clang will close the current gap before 4.0 is done.

Keep in mind my [comment above](https://github.com/android-ndk/ndk/issues/26#issuecomment-198067100). We have many other reasons to choose Clang, and do not have the resources to pursue both.

**Comment by bog-dan-ro** [comment]
@DanAlbert  @stephenhines : I understand that you don't have resources to maintain it (which sounds like a joke to me ... who could imagine that google can't afford to pay a gcc hacker to maintain it), but  why don't you accept community contributions?

@jcelerier @DoDoENT My feeling is that the whole story is not about which compiler is better for google customers, instead is about control and what is better for Google. Google is one of the most GPL haters out there (or at least this is how it looks like), and an BDS like license is more "suitable" for them... Why? Well because the BSD licence allows the Google to choose what (or if) they share back with the community. Again, this is my **personal** feeling...

**Comment by guruz** [comment]
BTW, it's in Qt the Qt-for-Android Known Issues :-(
https://wiki.qt.io/Qt_for_Android_known_issues

> There is a bug in GCC in the latest Android NDK, making it impossible to use it for building Qt. The bug has not been fixed yet, and it's recommended to use Android NDK r10e. NDK r15 produces applications that fail with the error message 'This application failed to start because it could not find or load the Qt platform plugin "android"'. See also the bug report.

**Comment by DanAlbert** [comment]
The bug referred to (https://github.com/android-ndk/ndk/issues/67) is a GCC bug. Use Clang and you won't have a problem.

**Comment by ehem** [comment]
Until standard Linux kernels can be built without extra patches, keeping a working GCC around is pretty valuable.  Looks like Google is aggressively pushing Qualcomm off of 3.18, but until every device is off 3.18 it needs to stay.

Really awful reason, but it is an issue.

**Comment by stephenhines** [comment]
It's not an issue if none of our devices are using GCC for their kernels. Again, feel free to use whichever compiler you like, but we are no longer actively supporting GCC (just like I mentioned last year). https://youtu.be/6l4DtR5exwo if you want to see our talk about getting the kernel and the rest of Android over to Clang.

**Comment by jcelerier** [comment]
@stephenhines : we aren't free to use "whatever compiler we like" : the choice is between an old GCC and a new Clang. If at least there was a procedure somewhere to build a more recent GCC that works with the android ndk it would be fine.

Besides, as of today, up-to-date GCC still mostly runs circles around Clang in terms of produced code performance: https://www.phoronix.com/scan.php?page=article&item=gcc-clang-eoy2017&num=4

This has a direct effect on the battery consumption of the software.

**Comment by DanAlbert** [comment]
> Until standard Linux kernels can be built without extra patches, keeping a working GCC around is pretty valuable.

The NDK compilers are not guaranteed to work for the kernel at all. The kernel compilers come from the prebuilts/gcc/... project of the given kernel manifest project.

**Comment by DanAlbert** [comment]
> If at least there was a procedure somewhere to build a more recent GCC that works with the android ndk it would be fine.

https://android.googlesource.com/toolchain/gcc/+/master/README.md

**Comment by Raulvo** [comment]
I would rather invest in developing GCC instead of switching to a compiler which does not provide feedback to the community and has less features. Where is LLVM's OpenMP 4.5 and 5.0? And OpenACC 2.0?


As for C++ standards:
https://gcc.gnu.org/projects/cxx-status.html
https://clang.llvm.org/cxx_status.html

The rest is bullshit. Fuzzing, diagnostics ... all can be contributed without minor further maintenance.

**Comment by snow8gaia** [comment]
The answer to #26 is use Clang. Not GCC.

**Comment by DanAlbert** [comment]
Using Clang on Windows is the same as using Clang on Linux or Darwin when it comes to the NDK. The NDK compilers are not intended to compile *for* Windows.

**Comment by vczh** [comment]
@DanAlbert It should, big companies are using it this way.

**Comment by ytrezq** [comment]
> Thanks for the updates on GCC. We still have no plans to continue maintaining it, but I am glad that others in the community are still working on it.

This is problematic as the Android’s kernel still requires gcc.

**Comment by jmgao** [comment]
> This is problematic as the Android’s kernel still requires gcc.

Pixels have been shipping with clang-built kernels for ~3 years now.

**Comment by ytrezq** [comment]
@jmgao But Samsung kernels and others still require gcc 4.9 and in fact their official binary uses gcc 4.9.
> Pixels have been shipping with clang-built kernels for ~3 years now.

(also as someone who tend to favor performance, I’m not kind to run the kernel code as bytecode for a jit frontend).

**Comment by DanAlbert** [comment]
That's not how LLVM works. The bytecode is just an IR. It compiles down to machine code just like GCC does. Sometimes it performs better, sometimes it performs worse.

If Samsung wants to keep supporting GCC that's up to them.

**Comment by stephenhines** [comment]
It's actually part of the Android CDD that new devices ship with Clang-built kernels to ensure all relevant security features (CFI and more going forward) are enabled.

**Comment by LeapofAzzam** [comment]
Fuck clang

**Comment by expnkx** [comment]
I have successfully built the latest GCC 11 cross-toolchain on windows.

LLVM sucks. No concepts and ranges header file in 2021 LOL.

I am helping the GCC team to fix the compiler. Maybe I can release the cross compiler by myself.

**Comment by ytrezq** [comment]
@expnkx please share your build.

**Comment by expnkx** [comment]
> @expnkx please share your build and patched source tree!

I will. I will fix some issues with toolchains and strip binaries. Then release them.
Here is a toolchain for MinGW-w64.
https://github.com/expnkx/mingw-gcc

I have builtin a huge amount of different toolchains.

![image](https://user-images.githubusercontent.com/57303909/110664231-3852e900-8195-11eb-90be-6f7794adb961.png)

**Comment by expnkx** [comment]
I have fixed the bug manually and committed my patch to GCC.

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=99499

![working](https://user-images.githubusercontent.com/57303909/110714914-44a96700-81d2-11eb-96d0-3586e254dc27.PNG)
![iostream](https://user-images.githubusercontent.com/57303909/110714919-46732a80-81d2-11eb-9c11-3f1695579f59.PNG)
![image](https://user-images.githubusercontent.com/57303909/110714936-4ecb6580-81d2-11eb-832d-3db3f31ee59d.png)
![image](https://user-images.githubusercontent.com/57303909/110714947-53901980-81d2-11eb-83fb-2791c0ff469e.png)
We can also use musl toolchains. They also work.

EH is enabled. We do not disable EH nonsense. (Though i tweak the compiler to disable libstdcxx verbose, bad_alloc length_error etc. Disabling nonsense would never be an issue)

The only problem is that in android /system is readonly. We cannot install libstdc++.so to the operating system. That prevents dynamic linking with libstdc++. However, as long as we do not use iostream, they are totally fine. No issue at all. My fast_io library can do everything that iostream could do with zero binary bloats.

**Comment by DanAlbert** [comment]
Please find another forum for this conversation. Nothing wrong with using your own toolchains, but it'd be better if you created your own project for that discussion.

**Comment by ValZapod** [comment]
Armv9 (Galaxy S22 on snapdragon) is only supported on gcc for now. So that is funny.

**Comment by calidion** [comment]
evil decision.

**Comment by stephenhines** [comment]
> Armv9 (Galaxy S22 on snapdragon) is only supported on gcc for now. So that is funny.

Searching for `armv9` in [clang/test/Preprocessor/aarch64-target-features.c](https://github.com/llvm/llvm-project/blob/13a784f368ef062a7bd652829bcf8bbdd94dc659/clang/test/Preprocessor/aarch64-target-features.c) would show you that armv9 is indeed supported in Clang (and has been so for quite some time actually). I'm not sure that I see the relevance of armv9 for most NDK users right now, however, considering that the vast majority of aarch64 devices in use are going to be armv8 only, so you wouldn't necessarily want to use this ABI even for specific libraries to dynamically load on certain devices only.

**Comment by ValZapod** [comment]
Okay! BTW, gcc can be used as a pluggin to clang anyway. So it does not matter much.

**Comment by mkrupczak3** [comment]
Still here, still mad about this 😠

**Comment by DanAlbert** [comment]
Locking the thread as it stopped being constructive a very long time ago. If you have an issue with clang (a fixable one, not just "it isn't GCC"), file a bug.
