### ISSUE TITLE
Neon for x86 not enabled in Clang

### ISSUE THREAD

**Issue by caand** [android-ndk/ndk#260]
#### Description

arm_neon.h doesn't (conditionally) include the x86 intrinsics translation (ndk r11 and later). It just fails for x86:
#if !defined(__ARM_NEON)
#error "NEON support not enabled"
#endif

It used to be (in r10):
#if defined(__i386__)
#include "arm_neon_x86.h"
#else
#if !defined(__ARM_NEON)
#error "NEON support not enabled"
#endif

#### Environment Details

* NDK Version: r11 and later
* Build sytem: ndk-build
* Host OS: Windows
* Compiler: Clang
* ABI: x86, x86_64
* NDK API level: any
* Device API level: any

**Comment by pirama-arumuga-nainar** [comment]
This was a change local to the LLVM distributed in r10 (https://android-review.googlesource.com/#/c/110888/) that never made it to upstream.  It's unlikely this would be accepted upstream.

One possible approach to use Neon intrinsics on x86 would be to fetch such a header yourself: https://github.com/intel/ARM_NEON_2_x86_SSE.

**Comment by DanAlbert** [comment]
Reopening to get the docs fixed.

**Comment by qchong** [comment]
@caand Docs have been updated. Thanks for your feedback!

https://developer.android.com/ndk/guides/cpu-arm-neon.html
https://developer.android.com/ndk/guides/x86.html

**Comment by caand** [comment]
This seems to be a bad joke. We're going backwards.

Neon support existed since for ever, for all possible abis: armv7, x86, armv8, x86-64. Everything still works with gcc. For some reason I don't understand you chose to remove one header file in the clang toolchain. Fine, I've been adding it manually in R11, R12, R13, R14 and with this it also works with clang.
You cannot drop now all support for NEON except for armv7. Are you aware that armv8 has a hardware NEON unit (even more capable than armv7)? And with the header mentioned in this thread and still distributed in NDK R14 for gcc, NEON can be translated to SSE?

Please do the right thing and promote high-performance Android apps by adding back full support for NEON on all possible ABIs.

**Comment by DanAlbert** [comment]
I think some clarification might be needed: no additional changes have been made to the NDK (things are still as they were in r11 wrt neon).

I think the arm8 bit is another mistake in the docs. I'm actually not familiar with how this works for arm8 though. I assume there's nothing special that needs to be done and that we just need to say "and arm8" everywhere we mention NEON in the docs?

If NEON for x86 is something that's going to be supported in Clang, it needs to actually make it into Clang with upstream's blessing. Last time we spoke with Intel about this, they didn't want this in Clang (and they would have veto power on this change). It's generally wise to trust them when it comes to advice on writing high performance code for their chips :)

(Sorry for not having explained this until now. I thought I had, but I can't find it anywhere.)

> Please do the right thing and promote high-performance Android apps

To be clear, this is absolutely something we care about, we just think that doing so by pretending every ABI can behave like arm7 is not the right way to do this. AIUI this wasn't added to GCC to help performance on x86, but for the sake of making code written for ARM portable to x86. x86 has its own vector math intrinsics, and you will see equal or better performance by using those on x86 rather than emulating them.

You can actually have both performance *and* portability by using something like https://clang.llvm.org/docs/LanguageExtensions.html#vector-literals. This way you have portable code that the compiler will actually be supporting (i.e. will optimize better). If the compiler still isn't doing a good enough job with those, at that point drop down to the raw intrinsics, but I seriously doubt that x86 emulating arm intrinsics is going to out perform these (and it definitely won't out perform direct use of the x86 intrinsics).

C++17 is also adding vectorization support to the APIs in `<algorithm>` (http://en.cppreference.com/w/cpp/algorithm/execution_policy_tag_t#parallel_vector) for this kind of thing.

If, even given the above options, you *really* want to stick with using fake NEON on x86, we are working on a package manager that should make sharing code across NDK projects *much* easier. If we're right in assuming that the Clang community won't want to support fake x86 NEON, you could use that to share this "library" between projects as trivially as if it were a compiler header.

**Comment by caand** [comment]
Thank you Dan,

Yes, the docs are still misleading:
- Indeed, the .neon suffix and the LOCAL_ARM_NEON variable only make sense
(are needed) for armv7. However, they also work (are not rejected by the
build tools) with all the others, where they are not actually needed. They
used to be rejected for 64bit ABIs, but now they are silently ignored (good
behavior IMHO). Armv8 does have intrinsic neon support as is, it doesn't
need special setup - just include <arm_neon.h> (which somehow disappeared
from the guides).
- x86 and x86-64 have full set of intrinsics headers, but this is not
mentioned in the docs. By adding the neon2sse translation header, neon
intrinsics also work fine (it's ok to keep the file out of the
distribution, but please don't break this in some other way).

On performance: we're building apps with complex real-time computations and
I can state that:
- neon intrinsics give performance very close to hand-assembly, but are
much more friendly.
- neon beats renderscript and is much more flexible.
- llvm vector operations don't use the powerful multi-qword load/store, and
memory access is key to many algorithms.
- neon2sse gives same performance as native sse in most cases - we had to
go to native sse for x86 for maybe 1% of our computation code (not at all
for x86-64), for only marginal improvements. And it has the advantage that
you code once and compile for all.

Conclusion: please don't break this, it's very useful.

Thanks,
Calin Andrian

**Comment by DanAlbert** [comment]
Reopening to get the docs improved.

> - llvm vector operations don't use the powerful multi-qword load/store, and
memory access is key to many algorithms.

We should get this fixed then.

**Comment by qchong** [comment]
Fixed NEON support page to indicate support for ARMv8:
https://developer.android.com/ndk/guides/cpu-arm-neon.html

**Comment by stephenhines** [comment]
> > - llvm vector operations don't use the powerful multi-qword load/store, and
memory access is key to many algorithms.
> 
> We should get this fixed then.

Can you file a bug at https://bugs.llvm.org/ with your specific request about vector operations? Perhaps ARM can help with optimizing in this case.
