### ISSUE TITLE
`noreturn` cleanup in <android/log.h> hasn't made it to the NDK yet

### ISSUE THREAD

**Issue by enh** [android-ndk/ndk#271]
i fixed <android/log.h> to say `__noreturn__` rather than `noreturn` in https://android.googlesource.com/platform/system/core/+/665051ca6347ded0a44dc6a36a2467f663c101df but that hasn't made it to the NDK yet.

(found trying to build toybox with the NDK, since it does `#define noreturn __attribute__((__noreturn__))` and then includes <android/log.h>.)

**Comment by DanAlbert** [comment]
The NDK is currently fed from https://android.googlesource.com/platform/system/core/+/master/liblog/legacy-ndk-includes/log.h because the system's liblog had diverged enough to not be compatible with the NDK. It seems there's still a massive amount of churn in that project, so I was waiting for them to settle on what they actually wanted to do with it before moving the NDK over to it.

**Comment by enh** [comment]
https://android-review.googlesource.com/#/c/318258/

**Comment by DanAlbert** [comment]
Fix is in the platform now, but I still need to update the NDK with the latest.
