### ISSUE TITLE
ndk r13 can not rebuild llvm libc++ from source code

### ISSUE THREAD

**Issue by hongjunwang** [android-ndk/ndk#273]
For some reason, I need rebuild llvm libc++ runtime from source code(By use LIBCXX_FORCE_REBUILD := true in Application.mk). But after update ndk  to version r13, It doesn't work anymore.

The error message like this:
ndk-build
Android NDK: /Users/hongjunwang/Library/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/Android.mk: Cannot find module with tag 'external/libcxxabi' in import path    
Android NDK: Are you sure your NDK_MODULE_PATH variable is properly defined ?    
Android NDK: The following directories were searched:    
Android NDK:         
/Users/hongjunwang/Library/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/Android.mk:157: *** Android NDK: Aborting.    .  Stop.

According to the error message,  NDK missing part of the necessary source files! This problem exists on both ndk r13 and r14.

**Comment by DanAlbert** [comment]
Yeah, we don't support doing that out of the box any more. Not all the components you need to build libc++ are a part of the NDK.

If you really need to rebuild libc++, it's built as part of the NDK (follow https://android.googlesource.com/platform/ndk/+/master/README.md).

If there's something you need to change that's a change we should be making anyway, elaborate on what you need and we'll see if we can do anything.

**Comment by dg0yt** [comment]
> Not all the components you need to build libc++ are a part of the NDK.
> ... elaborate on what you need and we'll see if we can do anything.

Developers of GPL apps need to ship the full corresponding source code and build scripts. This includes libc++ which is not a system library on Android from the GPL point of view IIUC. Having to provide the full NDK sources and build scripts is a quite heavy requirement for being able to ship a GPL app which uses libc++, especially since it is not just about providing a single tarball or git repository but extra layers of indirection by `repo` magic on top of multiple git repositories.

This issue might become more relevant once Qt finds new NDKs stable enough to switch.
