### ISSUE TITLE
libunwind.a for ARM32

### ISSUE THREAD

**Issue by Veigres** [android-ndk/ndk#277]
ARM32 (armeabi and armeabi-v7a) links to both libunwind.a and libgcc.a when using libc++, and AFAIK both of them contains symbols for unwinding. I am wondering why you need two different libraries and why it is only ARM32 that needs to have libunwind.a as a separate library? How is this compared to the other ABIs, that do not have libunwind.a?

Out of curiosity I am also wondering whether the libunwind.a in the NDK is based on LLVM's libunwind or Savannah's libunwind (or maybe something else)?

Thanks!

**Comment by DanAlbert** [comment]
Some of this is historical, but last time I checked it's all still true:

The ARM EHABI support in libc++abi doesn't work with libgcc as an unwinder (libgcc doesn't expose all the things that libc++abi needs, I think libsupc++ had those things defined for itself, it's been a long time since I've looked at this). Because of that, we use libunwind (LLVM's) to support it. libgcc is used on arm32 for the non-unwinding things it provides (libgcc also contains all the compiler runtime stuff).

All other ABIs just use DWARF for unwinding, so they can happily use libgcc.

Someone in Android is actually in the process of writing a new unwinder since everything we've tried so far is bad in at least some way (either slow, fragile, or both, not to mention most of them are impossible to maintain). Once that's done we'll be switching Android over to that for every architecture.
