### ISSUE TITLE
r11b: ndk-which dosen't work

### ISSUE THREAD

**Issue by khirowatari** [android-ndk/ndk#29]
###  Windows x64
```
C:\android\android-ndk-r11b>ndk-which gcc
'ndk-which' is not recognized as an internal or external command,
operable program or batch file.
```

I tried rename "ndk-which" to "ndk-which.cmd"
```
C:\android\android-ndk-r11b>ndk-which.cmd gcc
'C:\android\android-ndk-r11b\\prebuilt\windows-x86_64\bin\ndk-which' is not recognized as an internal or external command,
operable program or batch file.
```

### Linux / Mac
```
$ ndk-which gcc
make: /home/android/android-ndk-r11b/prebuilt/linux-x86_64/bin/build/core/build-local.mk: No such file or directory
make: *** No rule to make target `/home/android/android-ndk-r11b/prebuilt/linux-x86_64/bin/build/core/build-local.mk'.  Stop.
/usr/lib/ccache/gcc
```

**Comment by DanAlbert** [comment]
Windows is WAI. It's a shell script, and has never had a Windows implementation. We could leave this open as a feature request to add such a script.

As for being broken on Linux/Mac... oops. Since the implementation script lives in the different directory, a path needs to be updated.

L30 should be:

```diff
-MYNDKDIR=`dirname $0`
+MYNDKDIR=`dirname $0`/../../..
```

Will get a fix out for that in r12.

**Comment by khirowatari** [comment]
Thanks. MYNDKDIR fix worked for me.

**Comment by DanAlbert** [comment]
https://android-review.googlesource.com/209541
