### ISSUE TITLE
NDK 13/14  :  outdated vulkan.h 

### ISSUE THREAD

**Issue by Sumenia** [android-ndk/ndk#303]
Hi,

As of today, official vulkan header is at version 41

In NDK 13
in the folder  /platforms/android-24/arch-arm64/usr/include/vulkan
the vulkan.h provided for platform-24 is only the version 22

In NDK 14 
in the folder  /platforms/android-24/arch-arm64/usr/include/vulkan
vulkan.h provided in platform-24 folder is the version 28

In NDK 14 ( unified header )
in the folder sysroot/usr/include/vulkan
the vulkan.h provided in the folder is version 13 !

For exemple, those VkFormat are missing, and my application fail to compile due to this outdated vulkan.h provided in the android sysroot.

VK_FORMAT_PVRTC1_2BPP_UNORM_BLOCK_IMG
VK_FORMAT_PVRTC1_4BPP_UNORM_BLOCK_IMG
VK_FORMAT_PVRTC2_2BPP_UNORM_BLOCK_IMG
VK_FORMAT_PVRTC2_4BPP_UNORM_BLOCK_IMG
VK_FORMAT_PVRTC1_2BPP_SRGB_BLOCK_IMG
VK_FORMAT_PVRTC1_4BPP_SRGB_BLOCK_IMG
VK_FORMAT_PVRTC2_2BPP_SRGB_BLOCK_IMG
VK_FORMAT_PVRTC2_4BPP_SRGB_BLOCK_IMG

I think the unified header folder should pack the latest vulkan.h.

**Comment by DanAlbert** [comment]
Thanks for spotting this! It looks like vulkan.h actually has been updated rather frequently and is currently resting at version 38... in the internal branch...

I'll send an email to the folks that own this and remind them that it needs to be in AOSP to make it to the NDK so this hopefully doesn't happen again in the future.

I'm also going to see about getting this updated in time for r14 stable. I'm a little hesitant to take a full drop from the platform because that actually includes a kernel UAPI update (I don't like making big changes after beta 2), but I think those are usually pretty safe. @enh, do you agree? If not we can take just the vulkan.h update.

**Comment by enh** [comment]
i don't think we've had to change anything else for the last few uapi header updates. they've been pretty boring.

**Comment by cferris1000** [comment]
That last few kernel uapi header updates have been pretty safe and haven't resulted in any code changes .

I am sitting on the update to the v4.10 kernel headers because that change is causing some problems. I'm trying to figure out the best way to handle the latest headers without having to change a lot of external projects. But I'm not ready to submit them yet.

**Comment by DanAlbert** [comment]
Okay, apparently getting it fully updated is going to be non-trivial, but I've at least prepped an update the get it in sync with the deprecated headers.

**Comment by DanAlbert** [comment]
The updated headers are also the new fortify stuff. I'm going to take just the changes we need for this and `cfsetspeed` rather than taking the full set.

**Comment by DanAlbert** [comment]
(we don't have a new enough Clang in the NDK to take the new fortify stuff even if we wanted it)

**Comment by enh** [comment]
(i did wonder about that.)

**Comment by DanAlbert** [comment]
Merged into r14. FYI, someone took the time to do the full update to 38 (thanks, Jesse!), so unified headers will actually be more up to date than the deprecated ones rather than just on par.

**Comment by Sumenia** [comment]
that's great news, thank you ! 
as vulkan.h is moving pretty fast, are you planning to keep it updated in each NDK release ?

**Comment by DanAlbert** [comment]
It will be updated as often as it gets updated in the platform. Updates are likely to speed and slow to match the platform release cycles (early in development we'll probably be tracking closely, but as we stabilize a build the updates will probably stop). The problem we had here (having the one we ship be out of date even though we had a more up to date one internally) shouldn't be a problem in the future though.
