### ISSUE TITLE
Compile error in regex_compiler.h when using std::wregex with Clang

### ISSUE THREAD

**Issue by hrydgard** [android-ndk/ndk#325]
#### Description

Compile error in regex_compiler.h (gnustl_static) when trying to use std::wregex using Clang.

Library/Android/sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/regex_compiler.h:413:20: error: non-type template argument is not a constant expression

    std::bitset<1 << (8 * sizeof(_CharT))>,

This can be fixed by changing the line to:

    std::bitset<1ULL << (8 * sizeof(_CharT))>,

The issue is that when _CharT is wchar_t, which is 32-bit, the 1 gets shifted by 32 and that's a compile error (shift larger than what fits inside the value).

This is the same error as in this old StackOverflow question:
http://stackoverflow.com/questions/27591153/clang-3-5-0-stdwregex-compile-error

#### Environment Details

* NDK Version: 14
* Build system: cmake, android studio
* Host OS: any
* Compiler: clang
* STL: gnustl_static
* NDK API level: 15

**Comment by DanAlbert** [comment]
We're moving away from gnustl in favor of libc++ since gnustl doesn't offer any benefits that libc++ doesn't once we sort out the libandroid_support bugs (planned for the next release, r15). Assuming all goes according to plan, we're expecting to remove it in r17 (called out on [our roadmap](https://android.googlesource.com/platform/ndk/+/master/docs/Roadmap.md#Remove-non_libc_STLs)).

Since the earliest we'd be able to make a fix for this would be the same release we get libandroid_support fixed in, I think it makes more sense to focus my time on the libc++ side.
