### ISSUE TITLE
dev-defaults.sh `get_toolchain_name_for_arch mips` still returns 'mips64el-linux-android' on r14b

### ISSUE THREAD

**Issue by N-Bz** [android-ndk/ndk#340]
#### Description

The r14b ndk (Pkg.Revision = 14.1.3816874) has reverted to mips32 toolchains, but the `get_toolchain_name_for_arch` function in `dev-defaults.sh` still returns `mips64el-linux-android` for when `mips` is given as an argument

Commit [344a55ae20c29e68bc7a17963c24351896021bda](https://android.googlesource.com/platform/ndk/+/344a55ae20c29e68bc7a17963c24351896021bda%5E%21/build/tools/dev-defaults.sh) introduced the change to the mips64 toolchain, but was not reverted.

#### Environment Details

* NDK Version: 14.1.3816874 (downloaded from https://developer.android.com/ndk/downloads/index.html)
* Build sytem: standalone toolchain
* Host OS: Ubuntu 14.04

**Comment by DanAlbert** [comment]
Is this actually causing issues? This is intentional. We use the mips64 toolchains to generate 32-bit mips code (with `-mips32` flag).

**Comment by N-Bz** [comment]
Our [build system](https://github.com/Parrot-Developers/alchemy) uses it to determine the actual name of the binaries in the generated toolchains `bin` directory, instead of listing the directory.

Basically, the tool calls
`TOOLCHAIN_NAME=$(get_toolchain_name_for_arch mips 4.9)`
then generates the toolchain
`make-standalone-toolchain.sh --platform=android-14 --arch=mips --install-dir=$TOOLCHAIN_DIR`
and expects to find the tools (in this example `objdump`) at the following path:
`$TOOLCHAIN_DIR/bin/$TOOLCHAIN_NAME-objdump`

This works perfectly fine on r13, where the `make-standalone-toolchain.sh` and `get_toolchain_name_for_arch` both uses `mispel-linux-android` prefix (and also fine on r14 where both used `mips64el-linux-android`, but with the issues from #310 ), but fails on r14b because of the difference.

It might be an error on our side to rely on `get_toolchain_name_for_arch` to get the toolchain binaries name prefix, but we currently don't have a better solution without hardcoding the name

For reference, the file in the build system which calls the function and create the standalone toolchain is [this one](https://github.com/Parrot-Developers/alchemy/blob/master/toolchains/linux/bionic/selection.mk)

I hope this clarified the issue.

**Comment by DanAlbert** [comment]
Okay, thanks for clarifying. Unfortunately this isn't something we'll be reverting. We can't actually revert that change without breaking our builds (we need that to point at the mips64 toolchain because that's what we use when building mips32 code).

> It might be an error on our side to rely on get_toolchain_name_for_arch to get the toolchain binaries name prefix, but we currently don't have a better solution without hardcoding the name

Not the cleanest solution, but the files in that directory will all have the same prefix, so wildcard matching on `*-objdump` will actually find the tools. It's only marginally better than hard coding, but given that we can't actually revert this I don't have a better short term solution.

All the shell scripts in build/tools are sort of a historical accident (with the exception of make-standalone-toolchain.sh/make_standalone_toolchain.py). Those are actually what we use to build the NDK itself, and really never should have been shipped. The only reason they still exist at all is because I haven't had time to finish converting our builds over to the new Python based system.

The good news is that at some point in the future I'm going to add some config files to the NDK that will describe the locations of toolchains/abis etc so that maintaining third-party build systems is less trouble. The reason I haven't done this yet is because I want to make sure that I get ndk-build and cmake to start using them before I ship them because otherwise they aren't well tested, and I want the schema for them to remain as stable as possible.

**Comment by N-Bz** [comment]
Thanks for the clarification. We'll patch this on our side then.
