### ISSUE TITLE
Android CMake YASM support

### ISSUE THREAD

**Issue by TheSombreroKid** [android-ndk/ndk#346]
--------------------------------------------------------------------------------

#### Description

Android CMake build system is unable to build .asm files or use the yasm tool. I am trying to build libjpegturbo with simd support, we currently have a ndk make file which successfully builds it and when trying to move over to cmake, it is trying to build the .asm files with clang, forcibly specifying yasm works except it's still passing c compiler options to yasm and no matter how aggressively I override CMAKE_CXX_FLAGS or other flags i can't get it to stop passing -target and a couple of other flags which yasm does not tolerate.

#### Environment Details

Not all of these will be relevant to every bug, but please provide as much
information as you can.

* NDK Version: 14.0.3770861
* Build sytem: cmake
* Host OS: Windows
* Compiler: Clang, Yasm
* ABI: x86
* STL: c++_static
* NDK API level: 21
* Device API level: 24

**Comment by DanAlbert** [comment]
I think this can maybe just use the NASM support in CMake?
 https://github.com/Kitware/CMake/blob/master/Modules/CMakeASM_NASMInformation.cmake

If you set `CMAKE_ASM_NASM_COMPILER` to point to the NDK's yasm, does this Just Work?

> we currently have a ndk make file which successfully builds it and when trying to move over to cmake

ndk-build isn't going anywhere, fwiw. If you're doing this because you prefer cmake then that makes sense, but if you think we're going to force you over to cmake that isn't the plan :)

**Comment by TheSombreroKid** [comment]
Hi, Thanks for the reply, I tried the built in NASM support with the following cmake commands: 
set(CMAKE_ASM_NASM_COMPILER "${ANDROID_NDK}/prebuilt/windows-x86_64/bin/yasm.exe")
set(CMAKE_ASM_NASM_SOURCE_FILE_EXTENSIONS asm)
include (CMakeASM_NASMInformation.cmake)
enable_language(ASM_NASM)
and it seems to have built the .o files but is having trouble linking them, being able to see the full build log here would be immensely helpful, I can't fathom why android studio is so eager to throw away logging in the gradle console (and also the logcat). nm shows the symbols are in the library with the leading underscore but clang seems to be looking to link a symbol without it, I'm still working on resolving that issue, but it should be possible to forward from here, thanks. For future reference there is a copy of CMakeASM_NASMInformation.cmake as part of cmakes builtin modules.

The main reason for switching is that ndk-build locks up android studio when i start it up, infinitely building symbols until it runs out of memory. The CMake integration, for whatever reason doesn't do that. It also has the added benefit of reducing our build times significantly. ndk-build doesn't seem capable of incremental building and a full rebuild has went from over 15 minutes to under 3 by switching. We also have 5 or 6 distinct build systems to maintain, one of which is cmake so getting android onto cmake would reduce maintenance overhead significantly.

**Comment by DanAlbert** [comment]
> nm shows the symbols are in the library with the leading underscore but clang seems to be looking to link a symbol without it

iirc this is a quirk of the Windows C ABI. It might be that the nasm support in cmake adds some flags to target Windows. If this doesn't work out of the box, we'll need to do something in the NDK, so I'll leave this open.

I'm not totally sure when I'll have time to look in to this. There's still a lot of work to do right now for Android O, so my pure NDK time is rather limited. If you wanted to keep poking at it in the mean time I'd be more than happy to review patches :)

> The main reason for switching is that ndk-build locks up android studio when i start it up, infinitely building symbols until it runs out of memory.

Please file a bug on this. Follow the instructions for Android Studio issues over at https://source.android.com/source/report-bugs.

> ndk-build doesn't seem capable of incremental building

It absolutely is. If that's not happening, please let the Studio folks know (as above) since that's probably an integration bug.

> We also have 5 or 6 distinct build systems to maintain, one of which is cmake so getting android onto cmake would reduce maintenance overhead significantly.

Understood. CMake definitely sounds like the right choice for you on this point alone.

**Comment by TheSombreroKid** [comment]
Hey, thanks for getting back again, I just want to say incase anyone stumbles on this thread that I did fix the issue at the time, the simd library LibJpegTurbo mangles the symbols manually to fix the Windows ABI issue and you need to pass an ELF flag to suppress it, which i'd forgotten to do, so it was my own fault.

**Comment by DanAlbert** [comment]
> the simd library LibJpegTurbo mangles the symbols manually to fix the Windows ABI issue and you need to pass an ELF flag to suppress it

Oh! That makes sense. Any chance you could provide a quick set of instructions for what you needed to do to get things working? I'll hand it off to our docs folks so this is easier to work out for the next person.

**Comment by TheSombreroKid** [comment]
No problem! Here is what I ended up with:

`if (ANDROID_ABI STREQUAL  "armeabi-v7a")
enable_language(ASM)
set(SIMD
#Arm .s neon simd sources go here
)
elseif( ANDROID_ABI STREQUAL "x86")
set(CMAKE_ASM_NASM_COMPILER "${ANDROID_NDK}/prebuilt/windows-x86_64/bin/yasm.exe")
set(CMAKE_ASM_NASM_SOURCE_FILE_EXTENSIONS asm)
include (CMakeASM_NASMInformation)
enable_language(ASM_NASM)
set(CMAKE_ASM_NASM_COMPILER_ARG1 "-DELF")

set(SIMD
#x86 .asm simd sources go here
}
endif()

add_library(library_name STATIC ${SIMD} )`

Currently we're only building 32 bit code but this should easily extend to 64 bit as long as you have 64 bit assemblies.
The -DELF compiler flag is used to suppress the exporting of mangled names microsofts linker expects to find in the libjpegturbo jsimd source files so probably isn't useful for other libraries. 
Currently this is hard coded to the windows build of the compiler and so won't build on other os's, it should be easy to detect the correct location but I haven't spent much time on that yet.
We include the CMakeASM_NASMInformation that ships with cmake so there's no need to provide your own and we set the extension for the NASM compiler so it knows to look out for .asm files and that's about it.
Thanks.

**Comment by DanAlbert** [comment]
I was actually able to simplify that even more. I added the toolchain configuration pieces to our toolchain file, and the only part I needed in my `CMakeLists.txt` was the `enable_language(ASM_NASM)`. Here's the change: https://android-review.googlesource.com/376176

I'll also get someone to note in our docs that the `enable_language` portion is needed, since it's non-obvious that yasm is spelled `ASM_NASM` in cmake.

Thanks a lot for investigating this!

**Comment by DanAlbert** [comment]
Filed a bug to get samples/docs added for yasm here: https://issuetracker.google.com/37515214

**Comment by DanAlbert** [comment]
Fixed this in r15.
