### ISSUE TITLE
OpenSL with Unified Header

### ISSUE THREAD

**Issue by supercairos** [android-ndk/ndk#357]
Hi,

I wanted to try the new upcoming feature and my app compatibility with Unified Header.
I followed this procedure to enable it: 
https://android-developers.googleblog.com/2017/03/introducing-android-native-development.html
and I added to my CMake config the argument: 
`arguments "APP_UNIFIED_HEADERS=true"`

When trying to use Unified Header my own project witch use OpenSL. 
The build fail with (many) errors:
` /Users/xxxx/Library/Android/sdk/ndk-bundle/sysroot/usr/include/SLES/OpenSLES_Android.h:101:13: error: unknown type name 'SLboolean'; did you mean 'jboolean'?  SLboolean enabled);`
... (more then 20 like this, clang stops at 20) about types being undeclared.

Toggling the above flag and disabling the Unified Header makes my build compile again.

In the blogpost, you're mentioning 3rd party to be not fully supported but they should compile fine.
It should only fail at link time and I believe my crash in at compile (not a C/C++ pro...) :
> The API #ifdef guards do not exist in third-party headers like those found in OpenGL. In those cases > you'll receive a link time error (undefined reference) rather than a compile time error if you use an API > that is not available in your targeted API level.

#### Environment Details

Not all of these will be relevant to every bug, but please provide as much
information as you can.

* NDK Version: Pkg.Revision = 14.1.3816874
* Build sytem: CMake with Gradle integration (Gradle 3.3, AS 2.3.1)
* Host OS: Mac (Darwin)
* Compiler: Clang
* ABI: 'x86', 'x86_64', 'armeabi', 'armeabi-v7a', 'arm64-v8a' (fails on all)
* STL: c++_static (std=c++11)
* NDK API level: 21
* Device API level: 21

**Comment by enh** [comment]
interesting. i don't understand why (maybe @gkasten knows), but aiui the audio folks intend OpenSLES_Android.h to _not_ be stand-alone, and that you need to manually include OpenSLES.h yourself before including it. it looks like old versions of the NDK actually forked this header and inserted the missing #include of OpenSLES.h at the top of OpenSLES_Android.h. because the unified headers are the exact same headers used in the platform, they effectively revert this local change.

so your workaround for now is to manually #include OpenSLES.h before you #include OpenSLES_Android.h, but i've always thought this was strange (we always consider it a bug for a libc header to not work stand-alone), so hopefully we can persuade gkasten that we should modify the platform header here...

**Comment by enh** [comment]
actually, looks like @gkasten already fixed this:

Make OpenSLES_Android.h also include OpenSLES.h

For convenience of app developers,
OpenSLES_Android.h now also includes OpenSLES.h, and
OpenMAXAL_Android.h now also includes OpenMAXAL.h, and

Test: platform and Android-specific test apps build OK
Bug: 36362923
Change-Id: I5f96d40292c2e545472e636c8dac147e89475e9b

but that fix isn't in r15 beta1, but should be in future releases. for now, you'll have to go with the workaround suggested in the previous comment.

**Comment by enh** [comment]
reopening until we actually have the change on the r15 release branch...

**Comment by supercairos** [comment]
Thanks for this quick reply! 
Indeed it works as expected if I include both OpenSLES.h && OpenSLES_Android.h :)
