### ISSUE TITLE
libc++_shared (both hard float abi variants) fail to load properly

### ISSUE THREAD

**Issue by thalosii** [android-ndk/ndk#39]
I've checked both the r11 and r10d releases of the libc++ library, and i'm pretty sure both suffer from the same issue.

Essentially they fail to resolve the symbol __aeabi_d2lz (note: this is only true for hard float abi variants - including the thumb hard float variants).

I've been able to work around it on some versions of android by providing a little shim library that pulls in this define from libgcc.a before attempting to load libc++shared but unfortunately this little trick doesnt seem to work on older variants of android. I'm guessing my only option might be to try and recompile the libc++ library. Anyways, just wanted to bring this up as an issue. 

this a super simple repro... just call LoadLibrary("c++_shared")... and you should see the issues...

**Comment by DanAlbert** [comment]
If I had to guess, this is already fixed in r12 by the rearranging I did to how be build libc++. It used to be built by some awful shell script, but now it's actually built by ndk-build. The old shell script must have been missing the linker flag for disallowing undefined symbols, because otherwise it should have complained at build time.

The other alternative here is that we build it against a libc.so that claims to have that symbol, but the device you're running on doesn't actually contain it.

I'll try to find some time to verify this in r12.

**Comment by DanAlbert** [comment]
I haven't had time to check this myself, but you can try https://github.com/android-ndk/ndk/wiki#current-beta-release

**Comment by DanAlbert** [comment]
Hard float ABIs were removed.

**Comment by 2php** [comment]
@DanAlbert How to enable -mfloat-abi=hard?

**Comment by DanAlbert** [comment]
[You don't](https://android.googlesource.com/platform/ndk/+/master/docs/HardFloatAbi.md). You can tag specific functions with `__attribute__((pcs("aapcs-vfp")))` if you want those functions to be invoked with the alternate function call ABI.
