### ISSUE TITLE
fix building boost with unified headers

### ISSUE THREAD

**Issue by DanAlbert** [android-ndk/ndk#395]
https://svn.boost.org/trac/boost/ticket/12863
https://github.com/android-ndk/ndk/issues/302
https://github.com/android-ndk/ndk/issues/394

Looks like we probably need to send this patch ourselves. Boost already has the fallback code iirc, we just need to add the `#if __ANDROID_API__ >= 21`.

**Comment by enh** [comment]
building boost 1.64.0 for Android arm32 API level 18 with r15-beta2, i get two failures:

```
In file included from libs/log/src/posix/ipc_reliable_message_queue.cpp:51:
./boost/interprocess/mapped_region.hpp:814:22: error: use of undeclared identifier 'posix_madvise'
         return 0 == posix_madvise(this->priv_map_address(), this->priv_map_size(), unix_advice);
                     ^
1 error generated.

...

In file included from ./boost/asio/detail/epoll_reactor.hpp:239:
./boost/asio/detail/impl/epoll_reactor.ipp:487:12: error: use of undeclared identifier 'epoll_create1'; did you mean 'epoll_create'?
  int fd = epoll_create1(EPOLL_CLOEXEC);
           ^~~~~~~~~~~~~
           epoll_create
/usr/local/google/boost/toolchain/bin/../sysroot/usr/include/sys/epoll.h:76:5: note: 'epoll_create' declared here
int epoll_create(int);
    ^
1 error generated.

```

if i copy the workaround we have to #undef EPOLL_CLOEXEC (which will be in r15), that just leaves the posix_madvise problem. since that's the same pattern (code checks for #define, and it's one we're supplying anyway, not getting from the uapi headers), i think it makes more sense to just leave boost alone and add the equivalent workaround. i'll upload a patch for that as soon as i've tested it.

**Comment by enh** [comment]
with https://android-review.googlesource.com/407478 :

```
The Boost C++ Libraries were successfully built!
```

**Comment by enh** [comment]
and as a reminder to myself next time i need to build boost: https://gist.github.com/enh/b2dc8e2cbbce7fffffde2135271b10fd shows how.

**Comment by enh** [comment]
https://android-review.googlesource.com/407478 submitted and cherrypicked to r15.

**Comment by DanAlbert** [comment]
It's in the platform, but I still need to pull the sysroot into the NDK. Leaving this open so I don't forget to do that.
