### ISSUE TITLE
r11 clang: undefined reference to 'isnan' '__isinf'

### ISSUE THREAD

**Issue by osfans** [android-ndk/ndk#44]
jni/include/boost/math/special_functions/fpclassify.hpp:538: error: undefined reference to 'isnan'
/opt/android-ndk/sources/cxx-stl/llvm-libc++/libcxx/include/cmath:393: error: undefined reference to '__isinf'
/usr/local/google/buildbot/out_dirs/aosp-ndk-r11-release/build/tmp/build-5996/build-libc++/ndk/sources/cxx-stl/llvm-libc++/../../android/support/src/stdio/strtod.c:3111: error: undefined reference to '__fpclassifyd'
/usr/local/google/buildbot/out_dirs/aosp-ndk-r11-release/build/tmp/build-5996/build-libc++/ndk/sources/cxx-stl/llvm-libc++/../../android/support/src/stdio/vfprintf.c:250: error: undefined reference to '__isfinite'

```
NDK_TOOLCHAIN_VERSION := clang
APP_PLATFORM := android-8
APP_STL := c++_static
```

**Comment by DanAlbert** [comment]
First, try android-9. android-8 is not supported.

If the issues are still present, it's likely that those are private symbols (I can't remember which ones are and aren't in the math library since some of those are implemented with macros and the actual public definition is named like a private symbol).

**Comment by DanAlbert** [comment]
Just checked, not a problem for the supported API levels.
