### ISSUE TITLE
AMediaCodec_signalEndOfInputStream should be marked as __INTRODUCED_IN(26)

### ISSUE THREAD

**Issue by alexcohn** [android-ndk/ndk#466]
#### Description

The unified header **NdkMediaCodec.h** declares `AMediaCodec_signalEndOfInputStream()` (and probably some other APIs) that are only exported in `platforms/android-26/arch-*/usr/lib/libmediandk.so`. This API is not even declared in `android-26/arch-*/usr/include/media/NdkMediaCodec.h`. The limitation is not mentioned in the [online reference](https://developer.android.com/ndk/reference/ndk_media_codec_8h.html#a66273badd50f8cc131984d113b206494).

Note that the [corresponding Java API](https://developer.android.com/reference/android/media/MediaCodec.html#signalEndOfInputStream()) was introduced at API 18, which makes the limitation of android-26 unexpected to the programmer.

#### Environment Details

* link: https://stackoverflow.com/q/45251937/192373
* NDK Version: 15.1.4119039.
* NDK API level: 21

**Comment by enh** [comment]
from the original bug (https://issuetracker.google.com/32746065) for this API: "createInputSurface() and setParameters() API are not present in NDK MediaCodec. (They are available in the java API). ... also added AMediaCodec_signalEndOfInputStream".

looks like none of these changes in 2017 have the relevant #ifs, probably easily missed because all the existing API was covered by a single file-wide API 21 check:

af42d3f | NdkMediaCodec: add AMediaCodec_signalEndOfInputStream
f373e84 | NdkMediaCodec: implement setParameters to signal dynamic parameters
85a5363 | NdkMediaCodec: implement createPersistenInputSurface and setInputSurface 
1943158 | NdkMediaCodec: implement createInputSurface

**Comment by alexcohn** [comment]
I wonder, how hard could it be to backport `AMediaCodec_signalEndOfInputStream` and others to API 21+? I have a [POC](https://github.com/alexcohn/native-camera2) that backports **libcamera2ndk.so** to API 23 (it could be API 21, but I could not find an API-21 device with camera2 beyond **legacy**).

**Comment by enh** [comment]
(i've reopened the original bug https://issuetracker.google.com/32746065.)

**Comment by enh** [comment]
(i've pinged the internal bug, since nothing seems to have happened in the intervening month.)

**Comment by enh** [comment]
AOSP master fix: https://android-review.googlesource.com/481777

**Comment by DanAlbert** [comment]
In r16
