### ISSUE TITLE
start/stop simpleperf from app method

### ISSUE THREAD

**Issue by brok85** [android-ndk/ndk#499]
I would like to profile an app while a specific action is executed. For example, I would like to automatically start simpleperf when a specific button starts executing (e.g., onClick is called) and stop it when the button execution finishes (e.g., onClick returns):

public onClick_button_method(view v){
 start_simpleperf();
... button code...
stop_simpleperf();
}

A simple implementation (i.e., shown above) it would be to just inject a code line in the app to execute a shell command such as ./simpleperf -e .... at the beginning of the button's method. However, I think this solution may introduce a long latency. If the injected line is synchronous there may be latency overhead, and if it is asynchronous the button execution may finish even before simpleperf actually starts recording. What would be a good way to achieve what I want to do?

Thanks for any help.

**Comment by yabinc** [comment]
I understand this need to only profile selected range of code. Starting and stopping simpleperf process isn't a good solution here, because the onClick function can't last longer than 60ms, and we need to run this function many times to get hot path.

For this situation, why don't you profile it as below:
1. start the Activity containing the button.
2. run app_profiler.py for like 10s.
3. click the button many times during the profiling time.
My idea is, if you want to profile some operations, just record profiling data while you do them. And the recording file will show what is hot in these operations. Note that by default simpleperf doesn't generate samples when a thread is sleeping, so you don't need to worry the profiling result is full of samples where the UI thread is waiting for events. Basically, I think profiling is mainly a global thing, and improving the speed of a function which takes little percentage of time doesn't make much sense. But feel free to let me know your idea and situation.

Actually, we have a work about building a native simpleperf_record library, which can be linked in apps and the app code can enable/disable stating/recording many times before profiling ends. This is mainly to measure the performance of a small section of code, which probably matches your need. But it can't be available soon, because some kernels are buggy and need testing, and the needed libc compatibility library isn't available yet.

**Comment by brok85** [comment]
Thanks for the advice. Actually I am doing something similar to what you have suggested above. 

The reason why I wanted to better integrate simpleperf with specific code sections is that I want to use  it at runtime while a normal user is interacting with the app. Thus, if I simply get performance counter data with 10s periods, there may be different code sections executed, thus I wouldn't know the actual data about the code section I wanted to monitor. 

Is there a way to use timestamps to have a report that includes only the samples collected between two specific time stamps? 

Thanks a lot.

**Comment by yabinc** [comment]
> The reason why I wanted to better integrate simpleperf with specific code sections is that I want to use it at runtime while a normal user is interacting with the app.

Do you mean to profile like below: start profiling via adb or by some control input of the app, unplug the usb cable, use the app for some hours, plug the usb cable, stop profiling and collect profiling data on host, check the profiling result.
For the above situation, I think it is easy to support, although profiling specific code sections still need to wait libsimpleperf_record library.

> Is there a way to use timestamps to have a report that includes only the samples collected between two specific time stamps?

Technically it is possible, but it requires a lot of user work. User need to write code to generate timestamps of begin/end profiling manually, store them in a file, and pass the file to simpleperf scripts. So although it is a faster solution, I still prefer to use libsimpleperf_record library. But it is not a lot of work, so I think I can give it a try, by supporting a python script, which can filter samples in perf.data based on things like timestamps. Thanks for inspiring me!

**Comment by seal2002** [comment]
Hello @yabinc ,
I am a video game programmer. For my job, I need to record the stage of game (such as Menu, Action Phase, Loading ...). Do the simple record can record when the application is running ? ex : Running the game, go to AP and start app_profiler.py ?
Thanks,
Seal

**Comment by donaldwuid** [comment]
Game developer too and have the same question here. How can my game automatically start Simpleperf recording during the whole gameplay scene? Therefore I can get more  realistic perf data from my test-team

**Comment by DanAlbert** [comment]
@yabinc: Is this still going to make it for r17? I'm happy to take simpleperf updates up until late April.

**Comment by yabinc** [comment]
Yes, I am working on it.

**Comment by DanAlbert** [comment]
@yabinc: If you want this to be in r17 beta 2 I'll need it checked in by Tuesday. If not, I'm still okay with taking simpleperf updates after beta 2 for r17 stable, so no rush.

**Comment by yabinc** [comment]
I don't plan to update simpleperf in r17 beta 2, because some changes are halfway or haven't done. I will update simpleperf before April 15 for r17 stable release.

**Comment by yabincui** [comment]
Fixed by adding run_simpleperf_without_usb_connection.py script, as in https://android-review.googlesource.com/c/platform/system/extras/+/663074. This will be in ndk r17 release, as in https://android-review.googlesource.com/c/platform/prebuilts/simpleperf/+/672509.
