### ISSUE TITLE
report-sample distinguish different performance counters

### ISSUE THREAD

**Issue by brok85** [android-ndk/ndk#531]
Hi, 
if I execute 

./simpleperf record -e cache-misses,context-switches ...

I can record various performance counters at the same time and see the report for each one of them. However, the report-sample returns the complete list of raw samples but does not seem to indicate the counter of each sample. How can I understand to which counter each samples in the report-sample refers to? 

Thanks a lot!

**Comment by yabinc** [comment]
The raw output of simpleperf report-sample cmd doesn't contain event type, and there is no guarantee of its format. To show the event type of each sample, there are three ways:
1. use `simpleperf report-sample --protobuf --show-callchain -o outfile`.
  The output is in protobuf format as in https://android.googlesource.com/platform/system/extras/+/master/simpleperf/report_sample.proto, and contains event_type_id for each sample.
2. use `simpleperf report-sample --protobuf --show-callchain -o outfile`. then use `simpleperf report-sample --dump-protobuf-report outfile` to dump the protobuf file.
3. write a python script like https://android.googlesource.com/platform/system/extras/+/master/simpleperf/scripts/report_sample.py, and you can access event of each sample by event = lib.GetEventOfCurrentSample(). I recommend this way because it is more flexible.

**Comment by brok85** [comment]
Hi,
I tried the first two methods but the event_type_id does not show up in the output file.

This is what I get from the second method above:

sample 1:
  time: 20351314509021
  event_count: 1
  thread_id: 20103
  callchain:
    vaddr_in_file: ffffffc000d7e94c
    file_id: 0
    symbol_id: 0
...

Am I doing something wrong?

Thanks

**Comment by yabinc** [comment]
Maybe you are using old ndk version. This is supported starting from ndk r16 Beta 1. https://developer.android.com/ndk/downloads/index.html

**Comment by brok85** [comment]
Thanks! I am working with r16 beta 1 version now.

I have noticed a few things changed. For example:

1) Previously, I would find simpleperf installed into the data/data/org.example.app folder of the device. Now simpleperf does not seem to be there. Is it somewhere else or with this version simpleperf is not copied anymore into the device?

2) Every time I record with the "python app_profiler.py ... " the app restarts, which is undesired for me. I would like the app not to restart because sometimes I need to profile only certain things without profiling the app launch and so on. How can I avoid the force restart? If I can do this I do not need an answer to 1)

Thanks a lot

**Comment by brok85** [comment]
I think I solved by commenting self._restart_app() in the app_profiler.py file. However, if you have a more elegant solution (e.g., an argument passed through command line), please let me know.

Thanks a lot for the help.

**Comment by yabinc** [comment]
To not restart the app, you can add -nc option in app_profiler.py and don't provide -a or -t option. Like below:
python app_profiler.py --app com.example.simpleperf.simpleperfexamplepurejava -nc

The README.md should contain documents about app_profiler.py options, I will add it.

**Comment by brok85** [comment]
Thanks a lot that worked!
