### ISSUE TITLE
too many files open error

### ISSUE THREAD

**Issue by brok85** [android-ndk/ndk#535]
Hi,
I want to execute the profiling with simpleperf with many performance counters at the same time. However, if I record more than 12 counters, I get the error "failed: Too many open files" for the 13th counter.

I know that I can easily solve the problem by using no more than 12 counters at each time. However, I was wandering if there is a way to fix the problem and record many more counters at once. This would decrease a lot my experimentation time.

Thanks a lot for the help.

**Comment by brok85** [comment]
I think I fixed the problem by opening adb shell and changing the max ulimit of file descriptors opened from the default 1024 to 10240 by executing:

ulimit -n 10240 

in the adb shell. Then, if I execute ./simpleperf directly inside the data/local/tmp folder I can record all the counters I wanted at once.

Now, the problem is that the change I made (ulimit -n 10240) is apparently kept only for the shell session opened. Thus, if I execute app_profiler from outside, I get the same error as before.

Maybe I need to make the ulimit -n 10240 persistent or global?

**Comment by yabinc** [comment]
I don't suggest recording many counters unless they are tracepoint events. Because records based on cpu-cycles are similar to records based on cpu-clock, or instructions. Recording only one of them is enough to find hot path. And recording many counters takes a lot of cpu time, and records may heavily lost. So it is better to focus on one counter at a time.

The number of opened files = counter num * cpu num * thread num. The limitation of opened file descriptors on Android is 1024. 
To solve the too many open files problem, one is to limit the number of monitored threads by -t option.
If on a rooted device, you can also increase the file descriptor limitation by 'ulimit -n 65536'. To use it in app_profiler.py, you can do as below:
def start_profiling(self):
        args = ['ulimit -n 65536 &&', '/data/local/tmp/simpleperf', 'record', self.config['record_options'], ...

**Comment by brok85** [comment]
I made that change but it says:

/system/bin/sh: ulimit: 65536 exceeds allowable nofiles(descriptors) limit

Maybe I should run it as root? How can I execute the app_profiler.py as root?

**Comment by enh** [comment]
(fwiw, in P the global fd limit will be 32Ki by default, the same as most desktops.)

**Comment by brok85** [comment]
I probably fixed it as follows:

args = ["su -c 'ulimit -n 10240 &&'",'/data/local/tmp/simpleperf', 'record', ...

"su -c 'root_coomand_to_exec'" is to execute a root command directly.
