### ISSUE TITLE
[unified headers] mmap(2) not declared when building for API < 21 with __USE_FILE_OFFSET64

### ISSUE THREAD

**Issue by grendello** [android-ndk/ndk#536]
#### Description

I'm working on converting [Xamarin.Android](https://github.com/xamarin/xamarin-android)'s native bits to build using NDK unified headers. We're currently using `NDK 14b` but I confirmed that the issue described below exists in `NDK r16 beta1` as well.

As part of the Xamarin.Android build we compile the [Mono](https://github.com/mono/mono) runtime whose configure defines `__USE_FILE_OFFSET64` and the runtime is built using `C99`. When compiling code that uses `mmap(2)` `sys/mman.h` is included from the architecture's include directory but then it fails with

    dlmalloc.c:3150:24: error: implicit declaration of function 'mmap' is invalid in C99 [-Werror,-Wimplicit-function-declaration]

which was puzzling until I looked at the header and found the following code:

```C
#if defined(__USE_FILE_OFFSET64)

#if __ANDROID_API__ >= 21
void* mmap(void* __addr, size_t __size, int __prot, int __flags, int __fd, off_t __offset) __RENAME(mmap64) __INTRODUCED_IN(21);
#endif /* __ANDROID_API__ >= 21 */

#else
void* mmap(void* __addr, size_t __size, int __prot, int __flags, int __fd, off_t __offset);
#endif
```

Since our `__ANDROID_API__` has the value of `9` and since we have `__USE_FILE_OFFSET64` defined, the 32-bit `mmap` declaration is omitted leading to the above error. Defining `__USE_FILE_OFFSET64`  should not have adverse affects on platforms which don't support `mmap64` so I think the check should be changed to:

```C
#if defined(__USE_FILE_OFFSET64) && __ANDROID_API__ >= 21
```

which would have the desired effect without breaking code that needs to build against older APIs.

#### Environment Details

Not all of these will be relevant to every bug, but please provide as much
information as you can.

* NDK Version: 14b, exists in 16 beta1 as well
* Build sytem: standalone toolchain
* Host OS: Linux (Ubuntu 17.4)
* Compiler: clang
* ABI: all
* STL: not used
* NDK API level: 9
* Device API level: n/a

**Comment by enh** [comment]
1. don't define `__USE_FILE_OFFSET64` --- that's an internal implementation detail. `_FILE_OFFSET_BITS=64` is publicly-tweakable knob.

2. you're wrong. you need to realize that the #else case effectively says off32_t, not off_t. so that function is *not* compatible with the ABI you selected. See https://android.googlesource.com/platform/bionic/+/master/docs/32-bit-abi.md for more details.

to go back to how things were, stop defining _FILE_OFFSET_BITS=64 on 32-bit Android.

**Comment by grendello** [comment]
1. We use `-D_FILE_OFFSET_BITS=64`, referring to `__USE_FILE_OFFSET64` was a shortcut as this is the most direct cause of the issue
2. `off_t` should be defined to whatever bitness is appropriate for the target. If the target supports 32-bit only, then it should be off32_t

The way things were (and are if using non-unified headers) is that the code builds with `-D_FILE_OFFSET_BITS=64` and has been working like that for many years now. So this is a breaking change IMHO

**Comment by enh** [comment]
true, it's a breaking change, but only because your old code was wrong.

you've asked for a combination we can't give you, and we're telling you so (rather than silently doing something different from what you asked).

**Comment by grendello** [comment]
Since the code for API9 would be 32-bit and since mmap64 doesn't exist there, it wouldn't break anything - this is the kind of backwards compatibility that doesn't pose any risk. I see your point, but I disagree that it's a necessary breakage in this case.

**Comment by DanAlbert** [comment]
There's some nuance here. `off64_t` is supported on 14 (9 is no longer supported in r15). If the only function you use that depends on an `off_t` is `lseek`, then `_FILE_OFFSET_BITS=64` does everything you need on 14.

I know that sounds like a really narrow use case, but the number of functions with 64-bit `off_t` support grows each release right up to O. If you actually want us to guarantee that setting `_FILE_OFFSET_BITS=64` doesn't break code that worked without it, we have to just remove the feature.

**Comment by grendello** [comment]
Here's the test [Mono uses to detect](https://github.com/mono/mono/blob/master/configure.ac#L1559-L1579) whether to use `-D_FILE_OFFSET_BITS=64`:

```
AC_DEFUN([LARGE_FILES], [
		large_CPPFLAGS=$CPPFLAGS
		CPPFLAGS="$CPPFLAGS $1"
		AC_TRY_COMPILE([
			#include <sys/types.h>
			#include <limits.h>
		], [
			/* Lifted this compile time assert method from: http://www.jaggersoft.com/pubs/CVu11_3.html */
			#define COMPILE_TIME_ASSERT(pred) \
				switch(0){case 0:case pred:;}
			COMPILE_TIME_ASSERT(sizeof(off_t) * CHAR_BIT == 64);
		], [
			AC_MSG_RESULT(ok)
			AC_DEFINE(HAVE_LARGE_FILE_SUPPORT, 1, [Have large file support])
			large_CPPFLAGS="$large_CPPFLAGS $1"
			large_offt=yes
		], [
			AC_MSG_RESULT(no)
		])
		CPPFLAGS=$large_CPPFLAGS
	])

	AC_MSG_CHECKING(if off_t is 64 bits wide)
	LARGE_FILES("")
	if test $large_offt = no; then
		AC_MSG_CHECKING(if _FILE_OFFSET_BITS=64 gives 64 bit off_t)
		LARGE_FILES("-D_FILE_OFFSET_BITS=64")
fi
```
and here's the relevant fragment from NDK's `sys/types.h`:

```C
#if defined(__USE_FILE_OFFSET64) || defined(__LP64__)
typedef int64_t off_t;
typedef off_t loff_t;
typedef loff_t off64_t;
#else
/* This historical accident means that we had a 32-bit off_t on 32-bit architectures. */
typedef __kernel_off_t off_t;
typedef __kernel_loff_t loff_t;
typedef loff_t off64_t;
#endif
```

In my opinion, the `configure` test does the right thing - it sets `-D_FILE_OFFSET_BITS=64` to check whether the **platform** supports it and with `__ANDROID_API__` being `9` the expectation is that the header will use that particular API level to make the decision on whether or not 64-bit offsets are supported. I don't see error on our side since this code has been reliably working for many years on many platforms (not just Linux). I still think this is a bug in NDK. Since `off64_t` is not supported before 14, it shouldn't be reported as such before that API.

@DanAlbert I'm a bit confused with your statement regarding `API 9` support being dropped in `r15` - I checked and the platform headers are present even in `r16 beta1`? We're considering building against 12 or 14 as the lowest common denominator, would you recommend we do that instead of building against 9?

**Comment by DanAlbert** [comment]
> Since off64_t is not supported before 14, it shouldn't be reported as such before that API.

It was supported in 9. It's supported in every API level. The set of functions that are available with `_FILE_OFFSET_BITS=64` varies by release. If by "supported" you mean "has every function it would have _without_ `_FILE_OFFSET_BITS=64`", only O supports this. I think it's a bad idea to remove a feature (one that saves a lot of effort in supporting 4GB+ files) that works just fine for correct code just so incorrect code doesn't have to make a minor change.

The way I see it we have a few options:

1. Status quo. The only code that doesn't build is the code that is (possibly subtly, thanks to configure) incorrect. If people really need the support on older API levels, they can have it.

I much prefer this option. Before anyone assumes, it's roughly no effort to switch to the other options, so I'm not choosing this one simply because it doesn't require me to do any work :)

I will _always_ take the stance that we should be providing the best experience to correct code. I understand that "correct" here might be seen as a rather nit-picky difference, but changing your `off_t` is in fact changing your ABI, so configure should be passing that for _all_ of the checks it make. If it did, it would have correctly determined that the platform does not support `mmap` for the given API level and ABI combination.

2. Ignore `_FILE_OFFSET_BITS=64` for all 32-bit ABIs until _all_ APIs are available. This is roughly equivalent to removing the feature entirely.

The "this is why we can't have nice things" option. This is the option that would save me the most work, and it's also the worst choice imo. As I said above, I don't think we should be avoiding improvements for the sake of not requiring minor source changes for things that were wrong in the first place.

3. Ignore `_FILE_OFFSET_BITS=64` until some API level when bionic has _most_ of the APIs covered, probably L.

The issues that resulted in this bug don't disappear, but they do become less common.

tbqh, it doesn't make much difference to me which of these options we go with. I don't need to use these APIs. I'm just assuming that there are more people that don't want us to remove this feature than there are that don't want to change their code. I could easily be wrong, but I don't know how to get data that doesn't have a huge sampling bias.

> @DanAlbert I'm a bit confused with your statement regarding API 9 support being dropped in r15 - I checked and the platform headers are present even in r16 beta1? We're considering building against 12 or 14 as the lowest common denominator, would you recommend we do that instead of building against 9?

I goofed and fixed ndk-build and CMake to pull lower API levels up to 14 automatically, but forgot to actually delete the old sysroots. r16 doesn't have pre-14 sysroots.

Yes, I recommend targeting a newer API level whenever possible. tbh even ics has not enough users to be worth the effort (it has fewer than gingerbread). According to https://twitter.com/minsdkversion, you should target 19 :) Obviously the play store console is going to be useful feedback here. If you have a ton of jelly bean users, probably don't want to switch to 19.

**Comment by grendello** [comment]
@DanAlbert thanks, we'll modify our code to work around this issue - it's the best solution it seems

**Comment by DanAlbert** [comment]
Happy to help :)

**Comment by grendello** [comment]
There's however one more issue. I'll reuse the space here, if you don't mind. This time it's SIGRTMIN/SIGRTMAX. They're defined as follows in `signal.h`:

```C
#define SIGRTMIN (__libc_current_sigrtmin())
#define SIGRTMAX (__libc_current_sigrtmax())

#if __ANDROID_API__ >= 21
int __libc_current_sigrtmin(void) __INTRODUCED_IN(21);
int __libc_current_sigrtmax(void) __INTRODUCED_IN(21);
#endif /* __ANDROID_API__ >= 21 */
```

This breaks the build on `API < 21` because the functions are undefined there. `asm/sigrtmin.h` has the kernel constants for the macros. We can work around it too, but would you mind adding an `#ifndef` around the definitions in `signal.h` to make the workaround less messy  for us?

**Comment by enh** [comment]
since you're already using configure, you could just change your configure script to test for each of the `off_t` functions you want to use, not just the type itself.

i do think there's something to be said for option 3, but we don't know how many folks are getting away with things in the present setup because they're only using functions that are available before API 21. as danalbert says, by definition we don't hear from those people.

as for SIGRTMIN/SIGRTMAX, <android/legacy_signal_inlines.h> should already be working around that for you?

**Comment by grendello** [comment]
`android/legacy_signal_inlines.h` includes `signal.h` and doesn't define `__libc_current_sigrt{min,max}` so it won't help

**Comment by enh** [comment]
did you look at the file?

```
#if __ANDROID_API__ < __ANDROID_API_L__

sighandler_t bsd_signal(int __signal, sighandler_t __handler) __REMOVED_IN(21);

/* These weren't introduced until L. */
int __libc_current_sigrtmax() __attribute__((__weak__)) __VERSIONER_NO_GUARD;
int __libc_current_sigrtmin() __attribute__((__weak__)) __VERSIONER_NO_GUARD;

static __inline int __ndk_legacy___libc_current_sigrtmax() {
  if (__libc_current_sigrtmax) return __libc_current_sigrtmax();
  return __SIGRTMAX; /* Should match __libc_current_sigrtmax. */
}

static __inline int __ndk_legacy___libc_current_sigrtmin() {
  if (__libc_current_sigrtmin) return __libc_current_sigrtmin();
  return __SIGRTMIN + 4; /* Should match __libc_current_sigrtmin. */
}

#undef SIGRTMAX
#define SIGRTMAX __ndk_legacy___libc_current_sigrtmax()
#undef SIGRTMIN
#define SIGRTMIN __ndk_legacy___libc_current_sigrtmin()
```

**Comment by grendello** [comment]
Yes I did. As I wrote, we're using NDK 14b version currently and it doesn't have the functions defined. I guess we'll need to update.
