### ISSUE TITLE
SimplePerf: Difference between Hardware events and raw events?

### ISSUE THREAD

**Issue by brok85** [android-ndk/ndk#550]
Hi,
In the list of events available there are multiple groups, including "Hardware Events" and "raw events provided by cpu pmu". What is the difference?

For example, what is the difference between cpu-cycles and raw-cpu-cycles? 

Where may I find more detailed information?

Thanks a lot for any info

**Comment by yabinc** [comment]
The performance monitoring unit (PMU) in cpu provides hardware counters to monitor performance events. But different architectures and cpu versions support different events, as shown in raw events. And the linux kernel wraps some raw events into general hardware and cache events. So basically hardware and cache events are subsets of raw events, but they provide a general interface (So we don't need to worry if we are running on x86 or arm, same hardware and cache event name always has the same meaning.)

The reason to provide raw events is because the kernel doesn't convert all raw events into hardware and cache events. If you can find events you are interested in in hardware and cache events, you can search it in raw events instead. 

cpu-cycles and raw-cpu-cycles are the same thing. if you stat -e cpu-cycles,raw-cpu-cycles at the same time, they have count values with only a small difference.

As in the output of simpleperf list raw, you can find doc below:
List of raw events provided by cpu pmu:
  # Please refer to PMU event numbers listed in ARMv8 manual for details.
  # A possible link is https://developer.arm.com/docs/ddi0487/latest/arm-architecture-reference-manual-armv8-for-armv8-a-architecture-profile.

**Comment by brok85** [comment]
Hi,
what is the difference between the software events and the hardware/cache events?

Thanks for any info!

**Comment by yabinc** [comment]
software events don't need support of PMU. They are events supported by the kernel:
cpu-clock: passed time in nanoseconds
task-clock: passed time in nanoseconds (as I know, it is the same as cpu-clock)
page-faults
context-switches
...
cpu-clock and task-clock are actually supported by hrtimer in the kernel. page-faults, context-switches and all tracepoint events are generated by specific functions in the kernel.

**Comment by brok85** [comment]
I see. One last question:

software events and hardware/cache events still use the same registers for the counting?

Thanks

**Comment by yabinc** [comment]
Don't know what you mean by registers.

**Comment by brok85** [comment]
I meant counters. I know there is a limited number of counters used to count the events. Are those counters used by software events too?

**Comment by yabinc** [comment]
hardware counters are resources in PMU, and are only used by hardware events, hwcache events and raw events.

**Comment by gollarx** [comment]
what is the supported event for cpu-cycles as it is not supporting in our devices? Any idea on this?
