### ISSUE TITLE
cannot find string.h file in "android-ndk-r16/sources/android/support/include "

### ISSUE THREAD

**Issue by jakiechris** [android-ndk/ndk#577]
in android-ndk-r12b, the path includes string.h file.

 where did it go?

**Comment by jakiechris** [comment]
https://www.phoronix.com/scan.php?page=news_item&px=Android-NDK-r16

GCC has been killed ...

so how to change c++ app project to llvm?

**Comment by alexcohn** [comment]
> how to change c++ app project to llvm?

This question definitely deserves detailed response from the developers. But in simple cases, you don't need to do much. If you work with **ndk-build** and set the compiler in **Application.mk**, this means that you should remove `NDK_TOOLCHAIN` or `NDK_TOOLCHAIN_VERSION`. For **CMakeLists.txt**, don't set `ANDROID_TOOLCHAIN`.

**Comment by DanAlbert** [comment]
And for standalone toolchains, just use the clang binary instead of the gcc one. Both are installed in a standalone toolchain. For other build systems, check with the build system maintainer.

A test case demonstrating the problem you're having is necessary. The information you've provided doesn't give me anything to go on. We have tests that show that trivial cases are not broken.
