### ISSUE TITLE
cannot locate symbol "__atomic_fetch_add_4"

### ISSUE THREAD

**Issue by amraboelela** [android-ndk/ndk#589]
https://bugs.swift.org/browse/SR-6504

I got this error while trying to run an app linking libfoundation and libdispatch
dlopen failed: cannot locate symbol "__atomic_fetch_add_4" referenced by "/data/app/com.example.addswift-1/lib/arm/libdispatch.so
 
Full error:
 
11-29 15:59:36.788 2983-2983/com.example.addswift E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.example.addswift, PID: 2983
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__atomic_fetch_add_4" referenced by "/data/app/com.example.addswift-1/lib/arm/libdispatch.so"...
at java.lang.Runtime.loadLibrary0(Runtime.java:977)
at java.lang.System.loadLibrary(System.java:1530)
at com.example.addswift.MainActivity.<clinit>(MainActivity.java:43)
at java.lang.Class.newInstance(Native Method)
at android.app.Instrumentation.newActivity(Instrumentation.java:1078)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2538)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
at android.app.ActivityThread.-wrap12(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6077)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by amraboelela** [comment]
CMakeLists.txt:

set(AndroidAppDir ${CMAKE_SOURCE_DIR}/../../../..)

add_library(AddSwift SHARED IMPORTED)
set_target_properties(AddSwift PROPERTIES IMPORTED_LOCATION
${AndroidAppDir}/libs/${ANDROID_ABI}/libAddSwift.so)

add_library(add-swift SHARED
            add-swift.c)

target_link_libraries(
                      add-swift
                      android
                      log
                      AddSwift
                      )

**Comment by amraboelela** [comment]
repo: https://github.com/amraboelela/AmrSwiftAndroid

**Comment by DanAlbert** [comment]
https://android.googlesource.com/platform/ndk/+/master/docs/user/common_problems.md#undefined-reference-to

**Comment by biasmv** [comment]
Just FYI, we were running into the same issue. In our case it was not enough to add `-latomic` to the linker option, but `-latomic` had to be listed as the last option, even after the C++ standard library.

I'm still not sure why we didn't get the missing symbol error during linking but only once the library gets loaded on the device. 🤷‍♂️

**Comment by DanAlbert** [comment]
If you're using a static variant of the STL, yes, -latomic has to appear after it.

> I'm still not sure why we didn't get the missing symbol error during linking but only once the library gets loaded on the device.

Easiest way to do this would be to not set `-Wl,--no-undefined` in your linker flags (ndk-build and our cmake toolchain file do this for you).

Another option would be that some library (call it libfoo) you're building against linked these with public visibility and got linked before libatomic which caused the symbol to not be included in your library (because it was provided by libfoo), but then the libfoo on the device did not actually contain that symbol. This doesn't happen if your link order is correct (all objects, all static libs, all shared libs, all of which are topologically ordered), but the only build system I know that does this properly is ndk-build. Our CMake toolchain file and ndk-build will both use `-Wl,--exclude-libs,libatomic.a` to prevent this from being a problem, but if the library you're getting this from wasn't build with either of those (or was built with an old NDK), that may not have happened.
