### ISSUE TITLE
default stl flavor not consistent between ndk-build and cmake-port?

### ISSUE THREAD

**Issue by ggfan** [android-ndk/ndk#595]
This is more like a question:  could the 2 build systems use the same default stl flavor?
For CMake, the default stl seems to be gnustl_static actually:
```java
if(NOT ANDROID_STL)
  set(ANDROID_STL gnustl_static)
endif()
```
that is inside build/cmake/android.toochain.cmake

the ndkbuild build system actually setting the default stl to system:
```
# Check that APP_STL is defined. If not, use the default value (system)
# otherwise, check that the name is correct.
APP_STL := $(strip $(APP_STL))
ifndef APP_STL
    APP_STL := system
else
    $(call ndk-stl-check,$(APP_STL))
endif
```
that is is inside file: `build/core/add-application.mk`

The info above is from android-ndk-r16b. I might read it wrong, kindly let me know, thanks!

**Comment by DanAlbert** [comment]
This is intentional. Rationale is explained in the commit message: https://android.googlesource.com/platform/ndk/+/9fb7e029a2ddc51d605202856ea194075f8bfe66.

**Comment by DanAlbert** [comment]
I'm not 100% convinced we shouldn't default to libc++ in ndk-build, but it seemed like the safe option since it's a larger change to go from system to libc++ than gnustl to libc++. If we get much feedback agreeing with you here, we can make the change.

Personally, I'd like to get rid of the system "STL" entirely. I'm of the opinion that you should either use a real STL or none at all.

**Comment by ggfan** [comment]
make sense, thank you for the information.
