### ISSUE TITLE
Over complicated way to download toolchain

### ISSUE THREAD

**Issue by Alkaris** [android-ndk/ndk#639]
Seems rather over complicated way to download the toolchain for the Android NDK just having to configure and download from another repo location, which could just be simplified to a simple `git clone` for a repository. Never seen such a convoluted way of downloading a repository source just for one thing. This complicates things and makes it all the more confusing on how to download anything when people just want to download toolkits and compile from the source files. Comes as no surprise that Google likes to over complicate things for convenience.

**Comment by enh** [comment]
the docs for building your own NDK are https://android.googlesource.com/platform/ndk.git/+/master/README.md

repo is just what Android uses for everything.

**Comment by DanAlbert** [comment]
If you're trying to *use* the NDK, you don't need to do any of that. Just download it from https://developer.android.com/ndk/downloads/index.html or via the SDK manager.

`repo` is only necessary if you're working *on* the NDK.

**Comment by stephenhines** [comment]
I think you both misread the request. They are looking for an easy way to *alter* the toolchain source files and then redeploy it as part of an NDK. That is a reasonable request, but not something that would be easy for us to do. The toolchain is indeed decoupled from the NDK build because the toolchain is used in many other places too! In fact, the NDK is usually the second stop for deployment. These toolchain prebuilts (not in the NDK packaging) are validated and deployed as part of Android's AOSP platform releases first. They also get used/deployed for building Android's Linux kernel and bootloaders. All of those projects also use distinct repositories to manage their releases/prebuilts.

As far as cutting down to 1 git clone operation, that's just an unfortunate reality of dealing with large, complex software systems. LLVM itself uses a handful of repositories today (llvm, clang, compiler-rt, libcxx, libcxxabi, openmp_llvm, clang-tools-extra, ...). They are moving towards a mono-repo world, but it isn't here yet. Even when that happens, we will still want our own git project for maintaining useful tools/scripts/etc. for building/packaging/verifying the toolchain. Keeping that separate makes it easy to ensure that the rest of the source base is consistent with upstream.

**Comment by enh** [comment]
no, i understood that. but "we use repo to manage collections of git projects" is just the way it is (for the foreseeable future), and if you want to build your own NDK, that's the entrance fee.
