### ISSUE TITLE
Simpleperf: can't unwind stack in some 32-bit libc functions

### ISSUE THREAD

**Issue by hardc0der** [android-ndk/ndk#701]
On Android 8.1 using simpleperf built from master when I run something like "simpleperf record -e task-clock -f 99 --call-graph dwarf" some call stacks end inside libc. For example, if my applications makes an ioctl() call the stack ends inside __ioctl. When I run "readelf -u libc.so" on the 32-bit libc it doesn't seem to have unwind table entries for this function. I was looking at the assembly source for this function in bionic and it does seem like it has some assembler directives to generate unwind information so I'm not sure what's going on. Any ideas?

**Comment by hardc0der** [comment]
Nevermind, the `app_profiler.py` script was pushing the stub `libc.so` to the _symfs_ directory because of the way I was creating the directory with unstripped libraries I pointed the script to. I am kind of curious how `simpleperf` is able to unwind through `__ioctl` because there is no unwind information for it if I dump `readelf -u libc.so`. It seems the unwind information for `__ioctl` may be merged somehow because if I pass the `--no-merge-exidx-entries` to the linker when linking `libc.so` the unwind entries for `__ioctl` do show up.

Sorry for the false alarm.

**Comment by enh** [comment]
our unwinding expert says:

This is because readelf -u only displays the arm exidx information, and all of the syscalls are using dwarf information. All of the assembler only routines are create dwarf unwind information on arm.

You can use the unwind_info tool (in AOSP) to display all of the unwind information for a library. It also understands our compressed sections, which readelf does not.

**Comment by hardc0der** [comment]
Thanks for the response. Super helpful and makes perfect sense!
