### ISSUE TITLE
libshaderc sources in NDK r.17 outdated 

### ISSUE THREAD

**Issue by alexcohn** [android-ndk/ndk#704]
#### Description

[Vulcan API samples building fails](https://stackoverflow.com/questions/50472588/vulcan-api-samples-building-fails) with NDK r.17. The [answer](https://stackoverflow.com/a/50474697/192373) explains the problem. Actually, the [fix for Clang 6.0](https://github.com/google/shaderc/commit/563bc6e87a43c38b5495469307922c768edbd191) was  ready 4 months ago, but **sources/third_party/shaderc** has not been updated.

#### Environment Details

* NDK Version: 17.0.4754217
* Compiler: Clang

**Comment by DanAlbert** [comment]
Thanks for refiling this from stack overflow, Alex.

Looks like we do have the updates in master. @dneto0: how risky would it be to merge all the updates in the master-ndk branch into the r17 branch for a hotfix? r17 has already released to stable, so if there's much risk we can just close this as fixed in r18 and move the bug over to the samples to suppress the warning for now.

**Comment by dneto0** [comment]
I think the only risk is in the interaction with the Vulkan loader and layers component, which also uses the SPIRV-Tools.
So as long as the following are updated together, the risk is minimal:

 - external/shaderc/*  (that's glslang, spirv-tools, spirv-headers, shaderc)
 - external/vulkan-validation-layers

**Comment by DanAlbert** [comment]
Okay, I'll pull updates for all of those into r17b.

**Comment by DanAlbert** [comment]
https://android-review.googlesource.com/q/topic:%2522shaderc-update%2522+(status:open+OR+status:merged)+branch:ndk-release-r17
