### ISSUE TITLE
fdprintf() available in stdio.h, but not libc.so

### ISSUE THREAD

**Issue by NHellFire** [android-ndk/ndk#72]
Same as this issue: https://code.google.com/p/android/issues/detail?id=11197
fdprintf() is missing from libc in the NDK again (since r11).

**Comment by DanAlbert** [comment]
Looks like it was dropped in https://android-review.googlesource.com/#/c/194561/

It was made private in bionic because there is no such function. `fdprintf` is not specified by C, POSIX, nor even a GNU extension.

It looks like we have the POSIX extension `dprintf`, but afaict that wasn't added until L, so there actually isn't any portable option for you (`dprintf` work on L and newer, but `fdprintf` won't work on 64-bit devices).

There aren't any good options for fixing this right now, but this is the kind of thing that will be fixed when we clean up our headers and add the compatibility library (we'll be able to provide an implementation of `dprintf` even on older devices).

For now, I think the best option is to use `fdopen`.

**Comment by DanAlbert** [comment]
Headers are fixed, but I'm going to leave this open so I remember to make sure `dprintf` makes it into the compatibility library.

The part of this that can be fixed in r14 is fixed, so I'm re-triaging this.

**Comment by DanAlbert** [comment]
Compatibility library got pushed to r16 because O ate all of r15's time.

**Comment by DanAlbert** [comment]
Fix ended up not needing to be added to the compatibility library. `dprintf` and `vdprintf` should work regardless of target API in r16.
