### ISSUE TITLE
Undefined references on arm64 ndk-build

### ISSUE THREAD

**Issue by IljaKosynkin** [android-ndk/ndk#761]
#### Description

Good morning/afternoon.
I stumbled upon quite strange behaviour/bug, when I was trying to make ndk-build with references to shared FFmpeg libraries for arm64 (*note that all other architectures are building just fine*). Essentially, I successfully built FFmpeg itself in form of shared libraries with Clang shipped with NDK, however in final stage of the building i.e. when I was trying to ndk-build test project linking against FFmpeg I got bunch of "undefined reference" errors. It seems to me like for some reason arm64 libraries are just ignored. I've checked presence of symbols in the built libraries and they are there.

You can check out the project here:
[Repo](https://github.com/IljaKosynkin/FFmpeg-Development-Kit/tree/ffmpeg-4.0)

It should be enough to navigate to:
android-ndk-r17b/sources/ffmpeg
and run:
./build.sh
to test out the problem. 
Note that I've included NDK itself into the case, to make sure it's easy to reproduce, so download may take some time.

I'm not exactly sure wherever it's actually a bug or there are some specifics to the arm64 itself, which I'm missing, however due to fact that all other architectures are building just fine I assume that there is something wrong and would appreciate any help. 

#### Environment Details

* NDK Version: 17.1.4828580
* Build system: ndk-build
* Host OS: OSX High Sierra 10.13.6
* Compiler: Clang
* ABI: arm64-v8a
* STL: c++_static
* NDK API level: 21-28
* Device API level: -

**Comment by IljaKosynkin** [comment]
Hello @rprichard, sorry for late response.
Hm, I will dig into soname issue, maybe there is configure flag for it, I totally missed it when was investigating .so files (I was primarily checking wherever missing symbols are actually defined in the lib, rather then validating lib itself). 
I believe there is an option in FFmpeg to turn off pthread, maybe it would help, I will try that out.
I will try standalone toolchain, however, shouldn't it be the same essentially? AFAIK, standalone toolchain is essentially just copied files from NDK, so result shouldn't differ, should it?
Thanks for the help! I will get back to this thread with results ASAP

**Comment by DanAlbert** [comment]
> AFAIK, standalone toolchain is essentially just copied files from NDK, so result shouldn't differ, should it?

Yes, but it's not just a slimmed down NDK, the various pieces are rearranged so that the compiler driver Just Works and you don't need to pass a million flags just to get things to compile. Rather than all the complex configuration for build.sh, you just need to point to the compiler/ar/etc and the driver will take care of the rest.

**Comment by IljaKosynkin** [comment]
@DanAlbert 
Yes, I understand this, but I would like to try to avoid using standalone toolchains, as usually you would like to build all supported archs rather then single one and thus it will require 4 toolchains, which would be quite hard drive intensive (last time I checked single toolchain took around 700MB ob disc, thus it will be around ~2.8GB for all archs). 

@rprichard 
It seems that --disable-pthreads passed to FFmpeg actually resolved the issue! I will close it now, as original issue is resolved and will proceed with testing libs on actual device with JNI code hooked up. 
Thanks a lot for help, I was struggling with this for weeks now!

**Comment by rprichard** [comment]
> If I pass -pthread to ld.gold, it rejects it.

Clarification: the ld.gold 1.12 in the NDK (as of r17b and r18 beta1) rejects `-pthread` because it doesn't recognize `-p`. The newer gold 1.15 on my Linux machine *does* recognize both `-p` and `-pthread` (by expanding `-pthread` into 3 arguments).

lld doesn't seem to allow combining short options, and it also doesn't recognize `-p`. The ld CLI has single-dash word options like `-pie` and `-plugin`, so maybe it's good if lld doesn't allow that idiom.

(The gold 1.15 --help string for `-p` is: `Ignored for ARM compatibility`)
