### ISSUE TITLE
CRT object file requires executable stack with r18b2 but not with r17

### ISSUE THREAD

**Issue by acmorrow** [android-ndk/ndk#779]
#### Description

The basic issue is that changing one of our scripts from running with r17 to r18b2

```
         unzip $SDK_PACKAGE
-        yes | ./tools/bin/sdkmanager --channel=0 \
+        yes | ./tools/bin/sdkmanager --channel=1 \
```

has caused novel warnings in the `channel=1` build when linking an SCons configure probe for the availability of `-Wl,-z,noexecstack`, leading to a failed build. The following SCons configure log section demonstrates the issue:

```
 [2018/08/28 09:12:48.828] scons: Configure: Checking if linker supports -Wl,-z,noexecstack...
 [2018/08/28 09:12:48.828] build/scons/8c8b3dbd/sconf_temp/conftest_46.c <-
 [2018/08/28 09:12:48.828]   |
 [2018/08/28 09:12:48.828]   |#include <stdlib.h>
 [2018/08/28 09:12:48.828]   |#include <stdio.h>
 [2018/08/28 09:12:48.828]   |int main() {
 [2018/08/28 09:12:48.828]   |    printf("Hello, World!");
 [2018/08/28 09:12:48.828]   |    return EXIT_SUCCESS;
 [2018/08/28 09:12:48.828]   |}
 [2018/08/28 09:12:48.828] /data/mci/9f77cfe0c2de406a008155c85afb02f5/android_toolchain-x86_64-21/bin/clang -o build/scons/8c8b3dbd/sconf_temp/conftest_46.o -c -std=c11 -fno-omit-frame-pointer -fno-strict-aliasing -ggdb -pthread -Wall -Wsign-compare -Wno-unknown-pragmas -Winvalid-pch -Werror -Os -Wno-unused-local-typedefs -Wno-unused-function -Wno-unused-private-field -Wno-deprecated-declarations -Wno-tautological-constant-out-of-range-compare -Wno-tautological-constant-compare -Wno-tautological-unsigned-zero-compare -Wno-tautological-unsigned-enum-zero-compare -Wno-unused-const-variable -Wno-missing-braces -Wno-inconsistent-missing-override -Wno-potentially-evaluated-expression -Wno-unused-lambda-capture -Wno-exceptions -fstack-protector-strong -Werror -fPIE -D__ANDROID_API__=21 -D_LIBCPP_ENABLE_CXX17_REMOVED_AUTO_PTR -DNDEBUG -D_XOPEN_SOURCE=700 -D_GNU_SOURCE build/scons/8c8b3dbd/sconf_temp/conftest_46.c
 [2018/08/28 09:12:48.828] /data/mci/9f77cfe0c2de406a008155c85afb02f5/android_toolchain-x86_64-21/bin/clang -o build/scons/8c8b3dbd/sconf_temp/conftest_46 -static-libstdc++ -fuse-ld=gold -Wl,--no-as-needed -pthread -Wl,-z,now -rdynamic -Wl,--fatal-warnings -fstack-protector-strong -Wl,--build-id -Wl,--hash-style=both -Wl,--warn-execstack -Wl,-z,noexecstack -pie build/scons/8c8b3dbd/sconf_temp/conftest_46.o  -Wl,-z,defs -lm
 [2018/08/28 09:12:48.828] clang70: warning: argument unused during compilation: '-static-libstdc++' [-Wunused-command-line-argument]
 [2018/08/28 09:12:48.828] /data/mci/9f77cfe0c2de406a008155c85afb02f5/android_toolchain-x86_64-21/bin/../lib/gcc/x86_64-linux-android/4.9.x/../../../../x86_64-linux-android/bin/ld.gold: warning: /data/mci/9f77cfe0c2de406a008155c85afb02f5/android_toolchain-x86_64-21/bin/../sysroot/usr/lib/../lib64/crtbegin_dynamic.o: requires executable stack
 [2018/08/28 09:12:48.828] /data/mci/9f77cfe0c2de406a008155c85afb02f5/android_toolchain-x86_64-21/bin/../lib/gcc/x86_64-linux-android/4.9.x/../../../../x86_64-linux-android/bin/ld.gold: warning: one or more inputs require executable stack, but -z noexecstack was given
 [2018/08/28 09:12:48.828] /data/mci/9f77cfe0c2de406a008155c85afb02f5/android_toolchain-x86_64-21/bin/../lib/gcc/x86_64-linux-android/4.9.x/../../../../x86_64-linux-android/bin/ld.gold: error: treating warnings as errors
 [2018/08/28 09:12:48.828] clang70: error: linker command failed with exit code 1 (use -v to see invocation)
 [2018/08/28 09:12:48.828] scons: Configure: no
```

What is most odd here is that the file that has been detected to require an executable stack is part of the CRT:

...*`crtbegin_dynamic.o: requires executable stack`*

So this is either a false positive warning/error, or the CRT in r18b2 has been damaged in such a way that it will force executable stacks in builds that do not explicitly forbid them, but fail builds that attempt to forbid them.

#### Environment Details

* NDK Version: r17, r18b2
* Build system: SCons
* Host OS: Linux, Ubuntu 16.04
* Compiler: Clang 
* ABI: All
* STL: libc++
* NDK API level: 21
* Device API level: Unsure

**Comment by acmorrow** [comment]
Here is a minimal repro script:

```
curl -O https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip
unzip sdk-tools-linux-4333796.zip

yes | ./tools/bin/sdkmanager --channel=1 \
            "platforms;android-28"  \
            "ndk-bundle"  \
            "emulator"  \
            "patcher;v4"  \
            "platform-tools"  \
            "build-tools;28.0.0" \
            "system-images;android-24;google_apis;x86_64"

python ./ndk-bundle/build/tools/make_standalone_toolchain.py --arch x86_64 --api 21 --stl=libc++ --install-dir ./standalone-toolchain

cat << EOF > hello_world.c
#include <stdlib.h>
#include <stdio.h>
int main() {
    printf("Hello, World!");
    return EXIT_SUCCESS;
}
EOF

./standalone-toolchain/bin/clang ./hello_world.c -o hello_world -Wl,--warn-execstack -Wl,-z,noexecstack -Wl,--fatal-warnings
```

Running this, for me, produces:

```
/home/andrew/asdf/droid/./standalone-toolchain/bin/../lib/gcc/x86_64-linux-android/4.9.x/../../../../x86_64-linux-android/bin/ld: warning: ./standalone-toolchain/bin/../sysroot/usr/lib/../lib64/crtbegin_dynamic.o: requires executable stack
/home/andrew/asdf/droid/./standalone-toolchain/bin/../lib/gcc/x86_64-linux-android/4.9.x/../../../../x86_64-linux-android/bin/ld: warning: one or more inputs require executable stack, but -z noexecstack was given
/home/andrew/asdf/droid/./standalone-toolchain/bin/../lib/gcc/x86_64-linux-android/4.9.x/../../../../x86_64-linux-android/bin/ld: error: treating warnings as errors
clang70: error: linker command failed with exit code 1 (use -v to see invocation)
```

But downgrading to `--channel=0` to use the r17 NDK results in a good build.

**Comment by alexcohn** [comment]
@acmorrow why do you need `-z noexecstack`?

**Comment by acmorrow** [comment]
@alexcohn -

Well, a few thoughts on that.

- First, and somewhat independently of your question: this worked in r17, but it doesn't work in r18b2. So either this is a regression or a deliberate change. If the latter, I'd like to understand the rationale; if the former, I suggest it should be fixed.

- Second, disabling executable stacks is a standard exploit mitigation technique. There shouldn't be any reason to disallow it, even if the threat model doesn't require it. The additional linker flags passed here are just to ensure that we don't have executable stacks when we expect not to. Furthermore, I can't think of a reason why Android would be different from other platforms where there are legitimate security reasons for disabling executable stacks. While having an executable stack is arguably not itself a security vulnerability, it certainly reduces the difficulty of crafting exploits for primary vulnerabilities.

- Third, this reproduction is reduced from a larger build system which automatically inserts `-Wl,--warn-execstack -Wl,-z,noexecstack -Wl,--fatal-warnings` on platforms which support those flags. I don't particularly want to special case disable it for Android unless I need to. But even then, if the Android toolchain doesn't support disabling executable stacks for some legitimate reason, I'd expect the toolchain to reject the flags as not supported, rather than accept them and then fail to link a trivial binary.

**Comment by rprichard** [comment]
I see that the `.note.GNU-stack` sections in crtbegin object files are marked executable in r18-beta2 on every architecture but arm64. IIRC, we switched from using gcc to using Clang to build the CRT files, so maybe that's got something to do with it? I'll keep digging...

**Comment by rprichard** [comment]
The crtbegin object files are generated with `-Wl,-r` and two inputs - a crtbegin C file and a crtbrand.S file. In r18, the crtbrand.o file has no `.note.GNU-stack` marker. The fix is probably as simple as compiling CRT objects with `-Wa,--noexecstack`. The NDK build systems already add `-Wa,--noexecstack` to CFLAGS.

The bug was caused by switching the CRT objects from GCC to Clang. The NDK's gcc driver automatically passed noexecstack to the linker and sometimes the assembler. Clang doesn't appear to do either of these:
 * gcc sometimes passed `--noexecstack` to `as` automatically (only for 32-bit targets?)
 * gcc automatically passed `-z noexecstack` to the linker (for all Android targets?)

The NDK's bfd linker for arm32/arm64 (not x86/x86-64) is a little buggy -- if both `-x [no]execstack` is passed and an input file has a `.note.GNU-stack` section, then the output file has *two* `.note.GNU-stack` sections. This applies to arm64 CRT objects in r17b. Maybe the fix for this issue should use gold on all targets.

AFAICT, we're still using bfd/gold to link crtbegin objects, even in the platform where we've mostly migrated to lld. lld's `-r` output never includes the `.note.GNU-stack` marker, so when we switch to lld, this bug could reappear. I filed https://bugs.llvm.org/show_bug.cgi?id=38747 for that issue.

**Comment by acmorrow** [comment]
@rprichard - Thank you, that is interesting background makes a lot of sense. A few comments and questions:

- We explicitly include the `.note` section in some assembly files in our project, but we added the `--warn-exectstack` and `-z,noexecstack` flags to our build because we have on occasion managed to break or disable the `.note`s in fun and surprising ways, leading to executable stacks, and those flags now prevent that. If the NDKs compiler driver is already adding the flags at the assembler level, maybe it should also auto add the `--warn-execstack` flag to the linker as a safety check (or, at least have a test case that does).

- We are currently hardcoding `-fuse-ld=gold` in our build, which seems to have been the correct choice rather than using the BFD linker, but I assume that at some point we will want to switch that to `-fuse-ld=lld`, per your comment. Should we be doing that now, since we are on r18 beta already, or is `lld` still going to be experimental in the r18 GA?

- Do you think there be an r18b3 containing a fix? We upgraded away from r17 because we couldn't get LTO to work in r17 on arm{32,64} due to issues supporting TLS, but it does work in r18. I'd prefer not to downgrade and back that out, but executable stacks feels worse.

**Comment by rprichard** [comment]
> If the NDKs compiler driver is already adding the flags at the assembler level, maybe it should also auto add the --warn-execstack flag to the linker as a safety check (or, at least have a test case that does).

I might add a regression test for this issue using `--warn-execstack`.

The current NDK driver (i.e. Clang's) doesn't pass the `-Wa,--noexecstack` or `-z noexecstack` flags automatically. Maybe it should, but it's much less useful with lld. Android's GCC driver used to.

`--warn-execstack` is only implemented in Gold. It's an unrecognized option error with bfd, and lld quietly ignores the option. [lld's idea is that executable stacks are obsolete](https://github.com/llvm-mirror/lld/blob/7cbb47f9f21250b2f653588eb0c1a3ab34be1348/ELF/InputFiles.cpp#L685), so it ignores `.note.GNU-stack` in its input files and requires an explicit `-z execstack` if you really want an executable stack. If you're already linking with `-z noexecstack`, then the stack won't be executable, and `--warn-execstack` has less value. I suppose it helps catch problems earlier (i.e. turns a run-time crash into a build failure)? Because we're moving to lld, I don't think we'd benefit from passing `--warn-execstack` automatically.

With gcc, taking the address of a nested function creates a trampoline that needs an executable stack. Clang doesn't support gcc's nested functions, so that's not an issue.

AFAIK, we still consider lld experimental in the stable r18 release.

I think this issue will be fixed in the stable r18 release. I'm not currently expecting a third beta.

**Comment by rprichard** [comment]
https://android-review.googlesource.com/c/platform/ndk/+/741454

**Comment by acmorrow** [comment]
I see this was cherry-picked back to r18. Thanks for fixing it!
