### ISSUE TITLE
Build System Maintainers Guide doesn't mention libandroid_support

### ISSUE THREAD

**Issue by enh** [android-ndk/ndk#811]
source: https://android.googlesource.com/platform/ndk/+/master/docs/BuildSystemMaintainers.md

getting the headers and libraries for libandroid_support right so that libc++ works on <21 is probably one of the tricker remaining issues for folks with their own build system?

**Comment by DanAlbert** [comment]
Nope. It's handled by the toolchain.

It may be worth a mention though since the way that happens is a little funky (libandroid_support's headers get installed to sysroot/usr/local/include). They actually can't be avoided in the case of 21+ right now. I'm hoping to clean this up by moving more stuff into bionic, but this is the current state.

**Comment by enh** [comment]
(my counter-argument was going to be "i know there's linker script cleverness, but that doesn't handle the include directories", but dan meant "it's handled by the r19 toolchain, and the docs are for r19". in which case, nothing to see here...)
