### ISSUE TITLE
NDK r19 beta 1 & 2: undefined reference to `operator new(unsigned long, std::align_val_t)'

### ISSUE THREAD

**Issue by andreya108** [android-ndk/ndk#869]
#### Description

I cannot link our project with ndk r19 with the following errors (alot):

```
/home/andrey/android-sdk-linux/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/new:250: undefined reference to `operator new(unsigned long, std::align_val_t)'
/home/andrey/android-sdk-linux/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/new:250: undefined reference to `operator new(unsigned long, std::align_val_t)'
/home/andrey/android-sdk-linux/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/new:250: undefined reference to `operator new(unsigned long, std::align_val_t)'
```
We're using c++17. Everything was fine with previous versions of ndk,
please help to figure out what is wrong.

I've looked inside libc++_shared.so and it indeed does not have aligned versions of new.

Test case: https://github.com/andreya108/ndk-issue-869

#### Environment Details

* NDK Version: r19 beta1, beta2
* Build system: cmake, standalone toolchain
* Host OS: Ubuntu 18.04.1 x86_64
* Compiler: clang
* ABI: arm64-v8a
* STL: libc++
* NDK API level: 21

**Comment by DanAlbert** [comment]
We can't do anything without a test case.

**Comment by DanAlbert** [comment]
Looks like this got filed in a different bug tracker back in November: https://issuetracker.google.com/119212208.

Was able to repro using the instructions there (out-of-the-box new project wizard, add `-std=c++1z` to `cppFlags` in the build.gradle).

I tried on Linux outside gradle with no issues. Haven't yet figured out if it's Mac specific or something weird about how gradle is invoking cmake.

@andreya108: could you please fill out the rest of the bug template that you deleted? That's in the template because we need it

**Comment by andreya108** [comment]
@DanAlbert Thanks a lot for the linked issue, it greatly helped to make a test case.

Here it is: https://drive.google.com/open?id=1HZrwcUjIhyFox1d6nFdQRYuWYSZZFeIQ

The problem arises when one makes debug build and -O0 and fno-limit-debug-info comes into play.

**Comment by andreya108** [comment]
p.s: I use Ubuntu 18.04.1 x86_64 as a host.

**Comment by andreya108** [comment]
Added the test case to github: https://github.com/andreya108/ndk-issue-869

**Comment by DanAlbert** [comment]
Thanks! That test case helped a lot. I can't actually get it to repro within Studio on my Linux machine, but your repro case does work.

It seems the problem is that Clang is eliminating calls to the aligned new/delete when optimizing. At `-O0` they are not optimized away, and for some reason those aren't available in libc++? They exist in the source but aren't present in the library. Will continue investigating.

**Comment by DanAlbert** [comment]
https://android-review.googlesource.com/c/platform/external/libcxx/+/847301

**Comment by andreya108** [comment]
Thank you for quick fix!
Is there any ndk r19 nightly build with integrated changes?

**Comment by DanAlbert** [comment]
Yep: https://android.googlesource.com/platform/ndk/+/master/docs/ContinuousBuilds.md

**Comment by DanAlbert** [comment]
(the change hasn't been submitted to the r19 branch yet, but will be soon)

**Comment by DanAlbert** [comment]
It is now. Build 5178939 will have the fix.
