### ISSUE TITLE
[BUG]error: use of undeclared identifier 'fseeko'

### ISSUE THREAD

**Issue by SravanaLakshmiSunkara** [android-ndk/ndk#956]
#### Description
When I am trying to build a boost library in Android using its source code, I am getting below error

> release|armeabi-v7a : D:/Android/Sdk/ndk->bundle/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/c++/v1\fstream:969:9: release|armeabi-v7a : error: use of undeclared identifier 'fseeko' release|armeabi-v7a : if (fseeko(__file_, __sp, SEEK_SET))

Below is my CMake
```

externalNativeBuild {
            cmake {
                cppFlags "-std=c++14 -frtti -fexceptions -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64"
                arguments '-DANDROID_SDK_ROOT=D:/Android/Sdk'
                arguments '-DANDROID_EMULATOR_AVD=PixelArm'
                arguments  '-DCMAKE_BUILD_TYPE=Debug'
                arguments '-DANDROID_PLATFORM=android-21'

            }
        }
        ndk {
            // Specifies the ABI configurations of your native
            // libraries Gradle should build and package with your APK.
            // need to also have ~ boost binaries built for each abi specified here
            abiFilters 'armeabi-v7a'
        }
```

#### Environment Details
NDK Version: r19c (19.2.5345600)
Build sytem: any
Compiler: clang++
ABI: any
STL: libc++
NDK API level: 21
Device API level: n/a

**Comment by enh** [comment]
you can't have `_FILE_OFFSET_BITS=64` *and* target API 21 *and* have _all_ the `off_t` functions available --- they simply didn't all exist back then. (the 64-bit `fseeko` was added in 24, for example, as you can see from `<stdio.h>`.)

you'll have to choose which you actually want. (if you're upgrading from an old NDK where `_FILE_OFFSET_BITS` did nothing, simply remove that. if you can target 24, change 21 to 24. if you don't need `fseeko`, rewrite that code [in this case, that's not an option since it's not your code].)

see https://android.googlesource.com/platform/bionic/+/master/docs/32-bit-abi.md#32_bit-and for more detail.
