### ISSUE TITLE
Dose NDK9 Support Android Studio Code  auto completion?

### ISSUE THREAD

**Issue by wuseal** [android-ndk/ndk#959]
I am using NDK R9 with ndk-build, not Cmake,  it can't make code Highlight and auto-completion, But with NDK R19, It works well with AndroidStudio, So from which NDK version could support Code completion?

For some reason, We can't upgrade NDK, And I hope I could have a good coding experience like Java In Android Studio.

**Comment by alexcohn** [comment]
It's a pity you cannot upgrade from NDK r9, there are quite a lot improvements (including security fixes) that you could find useful. Note that very soon, 32-bit-only apps will no longer be accepted on Play Store, thus upgrade is critical.

It's hard to tell which minimal version of NDK will collaborate with AS IDE, but keep in mind that there are interdependencies between the version of Android Gradle plugin and NDK version.

In my experience, there is little gain in porting the project from an old version of NDK to another old version: generally speaking (and I can afford to say this because I am not affiliated with the Google NDK development team), each iteration makes working with NDK less painful.

Having said all this, I can suggest a workaround for you: you can still build your production binaries with NDK r9 (not as a task integrated with IDE) and at the same time have latest NDK installed to sync the code for indexing, completion, etc.

**Comment by DanAlbert** [comment]
You'd probably need to use a very old version of the Gradle plugin. I don't know which version that would be (as the bug template said, this is the wrong place to ask Studio questions because we don't know the answers). Even then, no guarantees.

The thing we might be able to help with is unblocking your NDK upgrade. Why are you suck on r9?

**Comment by wuseal** [comment]
> It's a pity you cannot upgrade from NDK r9, there are quite a lot improvements (including security fixes) that you could find useful. Note that very soon, 32-bit-only apps will no longer be accepted on Play Store, thus upgrade is critical.
> 
> It's hard to tell which minimal version of NDK will collaborate with AS IDE, but keep in mind that there are interdependencies between the version of Android Gradle plugin and NDK version.
> 
> In my experience, there is little gain in porting the project from an old version of NDK to another old version: generally speaking (and I can afford to say this because I am not affiliated with the Google NDK development team), each iteration makes working with NDK less painful.
> 
> Having said all this, I can suggest a workaround for you: you can still build your production binaries with NDK r9 (not as a task integrated with IDE) and at the same time have latest NDK installed to sync the code for indexing, completion, etc.

Thanks! I got it, That's a quite good idea with developing C++ code in the latest version NDK, and build on R9 version, Very happy to receive your Patiently answer.

**Comment by wuseal** [comment]
@DanAlbert Thank you very much for your reply, For a lot of work on upgrading NDK,  our native code is huge, And some big Environment problem with WebRTC build. we don't think we have enough time to do the upgrade of NDK, Therefore, we decided not to upgrade temporarily. But in the future, we will definitely upgrade that.

**Comment by alexcohn** [comment]
As for WebRTC, we chose to use the official build environment. In out case, we could modify our code to plug in directly into the `libjingle_peerconnection_so.so`, but we also did some successful experiments linking with the static library.

**Comment by wuseal** [comment]
@alexcohn Yes, now we also build the WebRTC out as an `.a` file to be used in Android Studio Project, WebRTC build target Android Platform by using NDK r9 to build, And we have done many modifies in the WebRTC of `2011` version, therefore the upgrade of WebRTC is also a huge work, So we will keep using the old WebRTC,  And when NDK upgrade to r19, but WebRTC does not, I feel that the compile environment need many painful works to make the old WebRTC build pass.

**Comment by alexcohn** [comment]
We finally succeeded to take all our custom code off the WebRTC tree, thus making it easier to use fresh WebRTC release (still not plug and play). I would not say it was painless refactoring, but it was definitely worth it.

At any rate, however you build the library, as long as it is relatively stable, you can have the rest of your C++ code (the business logic, which changes more often) built with integrated Android Studio build tools and the latest NDK.

**Comment by wuseal** [comment]
@alexcohn Thanks, It looks very well, Maybe I will try as you said in the future,  For now, we decide not to upgrade WebRTC&NDK, I have taken your suggestion that coding and building in a separate environment.
Now my problem has been solved, although it is not so perfect.  Thanks  @alexcohn & @DanAlbert
