### ISSUE TITLE
outdated [LLVM] LibC++ "cmath" file causing performance loss in single-precision C++ math code

### ISSUE THREAD

**Issue by Abe149** [android-ndk/ndk#96]
The "cmath" file of the LibC++ includes shipped in the NDK is very outdated, leading to poor performance in C++ code that is written in "true C++ style", e.g. "exp(my_float)" rather than "expf(my_float)" as is required in C in order to get good performance.

The rules of C++ provide for overloading based on the type vector* of the parameter list*, and TTBOMK the C++ standard expects an implementation to provide the necessary "guts" [e.g. overloads] such that e.g. "exp(my_float)" will work correctly and efficiently rather than converting to "double" and then back for the result.

*: not using these words in the C++ "std::foo" sense.

I have developed a patch that can be applied directly to the NDK in order to solve this problem [tested and verified it solves it] until the NDK updates to a much-more-recent revision of LibC++.  This problem has been fixed upstream in LibC++ [at least as of revision 249742].

**Comment by Abe149** [comment]
For reference: the commit that AFAIK fixes this upstream:

  https://github.com/llvm-mirror/libcxx/commit/4faa3944c623cbaa711ec9d39338d8872d0cf9f1

  https://llvm.org/svn/llvm-project/libcxx/trunk@249742

**Comment by Abe149** [comment]
For reference: the commit that AFAIK fixes this upstream:

  https://github.com/llvm-mirror/libcxx/commit/4faa3944c623cbaa711ec9d39338d8872d0cf9f1

  https://llvm.org/svn/llvm-project/libcxx/trunk?r=249742

**Comment by DanAlbert** [comment]
I'm really hoping to get our libc++ situation sorted out soon, and the first part of that is getting us back to matching upstream. Until then, I think the floating point performance of cmath is probably the least frightening thing about the NDK's libc++...

I'd rather not take any patches to this project since the deviation from upstream is why it's so bad today.

**Comment by Abe149** [comment]
Thanks for your reply, Dan, even though it`s not exactly what I was hoping for.  ;-)

Is there any plan to remove the minimalistic/unmaintained C++ libraries from the NDK, e.g. the bespoke one[s] and "STLport"?

I`d also like to know about plans to remove GCC...

**Comment by Abe149** [comment]
Oh, also: I am willing to help and I believe I am authorized to spend a large amount of my work time on helping to make the update-to-upstream happen, but I need some help as I have found nothing but confusion so far...  please see my comments at <https://groups.google.com/forum/m/?fromgroups#!topic/android-ndk/tTJGkZo62U8> and <https://groups.google.com/forum/m/?fromgroups#!topic/android-ndk/oEHo36rTce4>.

**Comment by Abe149** [comment]
Actually, one of those comments I made on the "android-ndk" mailing list may be outdated-since-I-have-learned-more, since the file I wanted to patch seems to "live" inside an AOSP checkout at "<checkout>/ndk/sources/cxx-stl/llvm-libc++/libcxx/include/cmath".

**Comment by DanAlbert** [comment]
> Is there any plan to remove the minimalistic/unmaintained C++ libraries from the NDK, e.g. the bespoke one[s] and "STLport"?

I'll be removing the others pretty much as soon as libc++ in the NDK is reliable. They are all strictly worse than libc++ (whether because they are abandonware like stlport or people fear gnustl's GPL).

> I`d also like to know about plans to remove GCC...

Actually that's somewhat related to the libc++ issue. The only reliable way to get C++11 support right now is with gnustl, and some pieces of gnustl don't play nice with clang. Not sure exactly when we'll remove it, but it can't be before libc++ is in better shape.

> Oh, also: I am willing to help and I believe I am authorized to spend a large amount of my work time on helping to make the update-to-upstream happen

Great! I think a good way to start would actually be solving the much smaller problem of updating libunwind and libc++abi. libc++ is really hard because we didn't have all the necessary libc pieces until L (that's what `libandroid_support` poorly provides, but some cases were modifications to libc++ source), but the other two should be relatively simple. It's near the top of my ever slipping todo list, but if you wanted to look into that it would be much appreciated :)

>  but I need some help as I have found nothing but confusion so far... please see my comments at https://groups.google.com/forum/m/?fromgroups#!topic/android-ndk/tTJGkZo62U8 and https://groups.google.com/forum/m/?fromgroups#!topic/android-ndk/oEHo36rTce4.

Sorry for the lack of response so far. Looking through the log, it looks like the last mention of an update from upstream was https://android.googlesource.com/platform/ndk/+/f7a0340a82325c212ae8bcf6d433aacfa8cfdfcc, which says r210061. I don't know if that's correct or not, but it's the best I can make out from the logs :(

**Comment by DanAlbert** [comment]
https://github.com/android-ndk/ndk/issues/106
