### ISSUE TITLE
NDK 19 - libdl.a dlopen() returns nullptr but dlerror() doesn't have an error

### ISSUE THREAD

**Issue by H-G-Hristov** [android-ndk/ndk#965]
Under what circumstances dlopen() will return nullptr and dlerror() will also return nullptr?

I try to run an SDL2 project, which SDLActivity loads the .so files but due to lack of any errors I am unable to guess what might be wrong.

(That bug label may be inappropriate.)

**Comment by enh** [comment]
> Under what circumstances dlopen() will return nullptr and dlerror() will also return nullptr?

if you have a static binary that's using `libdl.a` (which is a stub) rather than `libdl.so`.

that's an interesting point though --- we might want to make dlerror() return an error like "libdl.a is a stub".

your specific SDL2 issue is probably related to https://github.com/android-ndk/ndk/issues/929 (which is basically "why am i getting libdl.a instead of libdl.so?").

**Comment by Zingam** [comment]
Maybe it is just me but "libdl.a is a stub" will be still confusing. Is a more explicit error message possible?

**Comment by enh** [comment]
i went with "libdl.a is a stub --- use libdl.so instead" in https://android-review.googlesource.com/c/platform/bionic/+/948879.

**Comment by Zingam** [comment]
That's better. May I suggest to also add "the linked library" in there?

**Comment by enh** [comment]
where?
