### ISSUE TITLE
[BUG] Crash when unwinding callstack (in _Unwind_VRS_Pop function)

### ISSUE THREAD

**Issue by ignas2** [android-ndk/ndk#974]
#### Description

Our app retrieves callstack on crash and sends it to analytics services (with user consent). I've tried several different approaches on ARMv7a + Thumb with limited success (_Unwind_Backtrace, libunwind and libcorkscrew). Actually it worked on some devices (NVIDIA Shield TV with Android 7) but crashed on others (Samsung Galaxy S8 or S10e with Android 9). Callstack looked something like this:

```
libunity.so!_Unwind_VRS_Pop(_Unwind_Context * context, _Unwind_VRS_RegClass regclass, uint32_t discriminator, _Unwind_VRS_DataRepresentation representation) Line 907
	at \buildbot\src\android\ndk-release-r19\external\libunwind_llvm\src\Unwind-EHABI.cpp(907)
libunity.so!_Unwind_VRS_Interpret(_Unwind_Context * context, const uint32_t * data, size_t offset, size_t len) Line 275
	at \buildbot\src\android\ndk-release-r19\external\libunwind_llvm\src\Unwind-EHABI.cpp(275)
libunity.so!libunwind::UnwindCursor<libunwind::LocalAddressSpace, libunwind::Registers_arm>::stepWithEHABI(libunwind::UnwindCursor<libunwind::LocalAddressSpace, libunwind::Registers_arm> * this) Line 460
	at \buildbot\src\android\ndk-release-r19\external\libunwind_llvm\src\UnwindCursor.hpp(460)
libunity.so!libunwind::UnwindCursor<libunwind::LocalAddressSpace, libunwind::Registers_arm>::step(libunwind::UnwindCursor<libunwind::LocalAddressSpace, libunwind::Registers_arm> * this) Line 1339
	at \buildbot\src\android\ndk-release-r19\external\libunwind_llvm\src\UnwindCursor.hpp(1339)
libunity.so!(anonymous namespace)::unwindOneFrame(_Unwind_Control_Block * ucbp, _Unwind_Context * context) Line 184
	at \buildbot\src\android\ndk-release-r19\external\libunwind_llvm\src\Unwind-EHABI.cpp(184)
libunity.so!_Unwind_Backtrace(_Unwind_Trace_Fn callback, void * ref) Line 153
	at \buildbot\src\android\ndk-release-r19\external\libunwind_llvm\src\UnwindLevel1-gcc-ext.c(153)
libunity.so!CrashReporting::Android::LibUnwindHandler(int signum, siginfo_t * siginfo, void * sigcontext) Line 339
```

Turns out that this only happens on ARMv7 + Thumb if `raise(SIGSEGV)` function is used. Generating crash with something like `*(volatile int*)0 = 0;` unwinds callstack just fine. After some investigation I've noticed that `sp` register is stored in `r7`, then `r7` is modified by `raise` function (or rather other functions that are called by it) and after the signal unwinder restores `sp` from this messed up `r7` and fails with segmentation violation (after modifying `libunwind` myself I can make it fail without crashing).

Internet search points to this somewhat similar case:
https://sourceware.org/ml/libc-ports/2011-03/msg00045.html

So it seems that libc.so is somehow compiled incorrectly and that makes unwinder crash (it would fail silently if it was coded properly :)). Not sure if that makes this bug unrelated to NDK but please forward it to someone who can fix this.

I've made a small repro case. It can be built with ndk-build. You can also rename run.txt to run.cmd and use that to build and run repro program (Windows only).

#### Environment Details

* NDK Version: 19.2.5345600
* Build system: ndk-build
* Host OS: Windows
* ABI: armeabi-v7a (with Thumb)
* NDK API level: 19, 28
* Device API level: 28

#### Repro project

[unwind_crash.zip](https://github.com/android-ndk/ndk/files/3148664/unwind_crash.zip)

**Comment by enh** [comment]
@cferris1000 for unwinder...

(i'd have expected more trouble from abort() which actually has some inline assembly, but raise() is pretty boring, unless Samsung have changed it on those devices...)

**Comment by ignas2** [comment]
abort() is of no concern here. We aren't using it in production code. Also I'm aware that some of the functions are not signal safe but it's just a sample.

**Comment by cferris1000** [comment]
The problem is that none of the unwinder code you are using will work properly on arm32 when calling raise. The issue is that the raise function doesn't have arm exidx unwind information, it's using dwarf information to represent that fact that it's modifying r7. It's basically a thin wrapper on the tgkill function which is written in assembler.

_Unwind_Backtrace is meant for exception handling, and the only functions in libc that generate dwarf unwind information are pure assembler functions. All known assembler functions in libc are leaf functions so they can't generate an exception. This unwinder only knows anything about the arm exidx unwind information, you can see the arm exidx unwind information by running readelf -u on the arm 32 bit libc.so.

libcorkscrew is ancient, I'm not sure if it understands any dwarf information. And if it does, it probably doesn't understand dwarf 4 because it's pretty old.

Stock libunwind does understand dwarf (and maybe dwarf 4). However, it doesn't understand what to do if both exist. There is a version in the android source tree which does work properly on this code, but we have already deprecated it in favor of a new library called libunwindstack. This new library understands all of this information and more (including on P and Q, it can unwind through JIT code and can display frames from the ART interpreter, it also understands a special compressed debug section). Unfortunately, it's not in the ndk yet, but I hope to get this in this quarter. If you want to look at the code for this new unwinder, it's system/core/libunwindstack in aosp master. The libunwind code in aosp is in external/libunwind.

So this is why generating a crash through the forcing of a segfault works, it's not directly causing the segfault. But calling raise, makes you go through a function that doesn't have unwind information that any of your unwinders understand how to unwind.
