### ISSUE TITLE
[BUG] uuid.h is missing

### ISSUE THREAD

**Issue by rcdailey** [android-ndk/ndk#977]
Using NDK r19c with platform set to API 16, I do not see a uuid.h. I don't know a lot about this header file, but Google suggests it's dependent on the platform. So I guess someone just hasn't implemented it for the NDK yet.

There are third party libraries I am compiling using the Clang toolchain in the NDK. They fail to compile due to uuid.h missing. I am not aware of any alternative to use based on this platform. Is it a bug that this header is missing? If not, what alternatives can you suggest that don't involve introducing another external library?

**Comment by enh** [comment]
i don't know of any C library that includes this. i suspect you mean http://man7.org/linux/man-pages/man3/uuid.3.html which, as the man page says, "is part of the util-linux package since version 2.15.1 and is available from https://www.kernel.org/pub/linux/utils/util-linux/".

if you just need to generate a UUID, the algorithm is pretty trivial. see https://github.com/landley/toybox/blob/master/lib/lib.c#L1179 for a 0BSD-licensed implementation.

**Comment by nbtdev** [comment]
`e2fsprogs` provides `uuid.h`, and `e2fsprogs` is part of Android:

https://android.googlesource.com/platform/external/e2fsprogs/+/refs/heads/master/lib/uuid/uuid.h
